Repository tensorflow/models, pull requests merged in 2018-04, with the labels that each got.

#3813 Adding new checkpoints for Resnets
  official/resnet/README.md
Labels: cla: yes

#3841 After-the-fact response to @k-w-w 's review
  research/tensorrt/tensorrt.py
Labels: cla: yes

#3797 Add testing script for local lint and python test.
  official/utils/testing/scripts/presubmit.sh
Labels: cla: yes

#3845 Allow users passing master argument to avoid instantiating a TPUClusterResolver
  official/mnist/mnist_tpu.py
Labels: cla: yes

#3712 Image encoder: fix binary files parsed as UTF-8
  research/compression/image_encoder/decoder.py
  research/compression/image_encoder/encoder.py
  research/compression/image_encoder/msssim.py
Labels: cla: yes

#3828 First commit of learning_unsupervised_learning
  CODEOWNERS
  research/README.md
  research/learning_unsupervised_learning/.gitignore
  research/learning_unsupervised_learning/README.md
  research/learning_unsupervised_learning/__init__.py
  research/learning_unsupervised_learning/architectures/__init__.py
  research/learning_unsupervised_learning/architectures/common.py
  research/learning_unsupervised_learning/architectures/more_local_weight_update.py
  research/learning_unsupervised_learning/datasets/__init__.py
  research/learning_unsupervised_learning/datasets/common.py
  research/learning_unsupervised_learning/datasets/mnist.py
  research/learning_unsupervised_learning/evaluation.py
  research/learning_unsupervised_learning/meta_objective/__init__.py
  research/learning_unsupervised_learning/meta_objective/linear_regression.py
  research/learning_unsupervised_learning/meta_objective/sklearn.py
  research/learning_unsupervised_learning/meta_objective/utils.py
  research/learning_unsupervised_learning/optimizers.py
  research/learning_unsupervised_learning/run_eval.py
  research/learning_unsupervised_learning/summary_utils.py
  research/learning_unsupervised_learning/utils.py
  research/learning_unsupervised_learning/variable_replace.py
Labels: cla: yes

#3858 Fix the testing script exit code for python test.
  official/utils/testing/scripts/presubmit.sh
Labels: cla: yes

#3862 Added new model (differential_privacy/pate)
  CODEOWNERS
  research/README.md
  research/differential_privacy/pate/ICLR2018/README.md
  research/differential_privacy/pate/ICLR2018/download.py
  research/differential_privacy/pate/ICLR2018/generate_figures.sh
  research/differential_privacy/pate/ICLR2018/generate_table.sh
  research/differential_privacy/pate/ICLR2018/generate_table_data_independent.sh
  research/differential_privacy/pate/ICLR2018/plot_ls_q.py
  research/differential_privacy/pate/ICLR2018/rdp_bucketized.py
  research/differential_privacy/pate/ICLR2018/rdp_cumulative.py
  research/differential_privacy/pate/ICLR2018/rdp_flow.py
  research/differential_privacy/pate/ICLR2018/smooth_sensitivity_table.py
  research/differential_privacy/pate/README.md
  research/differential_privacy/pate/core.py
  research/differential_privacy/pate/core_test.py
  research/differential_privacy/pate/smooth_sensitivity.py
  research/differential_privacy/pate/smooth_sensitivity_test.py
Labels: cla: yes

#3860 Rename logging directory
  official/mnist/mnist.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/logs/__init__.py
  official/utils/logs/benchmark_uploader.py
  official/utils/logs/hooks.py
  official/utils/logs/hooks_helper.py
  official/utils/logs/hooks_helper_test.py
  official/utils/logs/hooks_test.py
  official/utils/logs/logger.py
  official/utils/logs/logger_test.py
  official/utils/logs/metric_hook.py
  official/utils/logs/metric_hook_test.py
  official/wide_deep/wide_deep.py
Labels: cla: yes

#3843 Fix eager demo's GPU cell
  samples/outreach/demos/eager_execution.ipynb
Labels: cla: yes

#3855 Fix momentum value flag from string => float
  research/attention_ocr/python/common_flags.py
Labels: cla: yes

#3852 Deeplab py3
  research/deeplab/core/xception_test.py
  research/deeplab/datasets/build_cityscapes_data.py
  research/deeplab/datasets/build_data.py
  research/deeplab/datasets/build_voc2012_data.py
  research/deeplab/eval.py
  research/deeplab/train.py
  research/deeplab/utils/train_utils.py
Labels: cla: yes

#3850 Add input images, labels, and output semantic predictions to summary
  research/deeplab/common.py
  research/deeplab/train.py
Labels: cla: yes

#3820 Add cyclegan to open source tensorflow/models
  research/gan/cyclegan/data_provider.py
  research/gan/cyclegan/data_provider_test.py
  research/gan/cyclegan/inference_demo.py
  research/gan/cyclegan/inference_demo_test.py
  research/gan/cyclegan/testdata/00500.jpg
  research/gan/cyclegan/train.py
  research/gan/cyclegan/train_test.py
  research/gan/pix2pix/networks_test.py
  research/gan/pix2pix/train.py
  research/gan/pix2pix/train_test.py
Labels: awaiting review, cla: yes, type:feature

#3888 Fix typo
  research/deeplab/core/feature_extractor.py
Labels: cla: yes

#3890 Allow mnist data to be writen to remote file system.
  official/mnist/dataset.py
Labels: cla: yes

#3898 Adding the team to the CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#3879 Touch-ups to eager's getting started guide
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#3899 Update data model download location to temp dir.
  official/mnist/dataset.py
Labels: cla: yes

#3911 fix typo
  research/deeplab/eval.py
Labels: cla: yes

#3917 Adding cast to fp32 for TensorRT no image case
  CODEOWNERS
  research/tensorrt/tensorrt.py
Labels: cla: yes

#3687 Add fp16 support to official ResNet.
  official/resnet/README.md
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_test.py
  official/resnet/resnet_model.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/arg_parsers/parsers_test.py
Labels: cla: yes

#3914 Update evaluation_protocols.md
  research/object_detection/g3doc/evaluation_protocols.md
Labels: cla: yes

#3744 Update create_pascal_tf_record.py
  research/object_detection/dataset_tools/create_pascal_tf_record.py
Labels: cla: yes

#3918 Updating DELF README
  research/delf/README.md
Labels: cla: no

#3863 Adding stop threshold logic
  official/mnist/mnist.py
  official/mnist/mnist_eager.py
  official/resnet/imagenet_test.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/misc/__init__.py
  official/utils/misc/model_helpers.py
  official/utils/misc/model_helpers_test.py
  official/wide_deep/wide_deep.py
Labels: cla: yes

#3941 Fix string to bytes conversion in deeplab data input. #3885
  research/deeplab/datasets/build_data.py
Labels: cla: yes

#3943 Add copyright header for testing script.
  official/utils/testing/scripts/presubmit.sh
Labels: cla: yes

#3921 change reference_data.py to use tf.gfile
  official/utils/testing/reference_data.py
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch_norm/expected_graph
  official/utils/testing/reference_data/resnet/batch_norm/tf_version.json
Labels: cla: yes

#3944 Pull doc fixes into version branch.
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#3942 official/mnist: Use tf.keras.Sequential
  official/mnist/mnist.py
  official/mnist/mnist_eager.py
  official/mnist/mnist_eager_test.py
  official/mnist/mnist_tpu.py
Labels: cla: yes

#3957 Correct a small typo
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#3745 Add link to the paper and the Tratz dataset
  research/lexnet_nc/README.md
Labels: cla: yes

#3641 fix issue 'could not satisfy explicit device'
  research/slim/train_image_classifier.py
Labels: cla: yes

#3977 Switch image link to https. Devsite wont load this over http.
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#3477 autoencoder: bugfix in initialization
  research/autoencoder/autoencoder_models/Autoencoder.py
Labels: cla: yes

#3998 Typo in ADE20K instructions.
  research/deeplab/g3doc/ade20k.md
Labels: cla: yes

#4004 Fix TensorRT test output and add int8 result.
  research/tensorrt/README.md
Labels: cla: yes

#4005 Adjust number of warmup loops
  research/tensorrt/tensorrt.py
Labels: cla: yes

#4008 Updating TensorRT output numbers
  research/tensorrt/README.md
Labels: cla: yes

#3955 Add minigo
  research/minigo/README.md
  research/minigo/__init__.py
  research/minigo/coords.py
  research/minigo/dualnet.py
  research/minigo/dualnet_model.py
  research/minigo/evaluation.py
  research/minigo/features.py
  research/minigo/go.py
  research/minigo/gtp_extensions.py
  research/minigo/gtp_wrapper.py
  research/minigo/mcts.py
  research/minigo/minigo.py
  research/minigo/model_params.py
  research/minigo/preprocessing.py
  research/minigo/selfplay_mcts.py
  research/minigo/sgf_wrapper.py
  research/minigo/strategies.py
  research/minigo/symmetries.py
  research/minigo/utils.py
Labels: cla: yes

#4003 Specify that pretraining MaskGAN is not optional.
  research/maskgan/README.md
Labels: cla: yes

#4033 Revert "Resnet distribution strategies (#3887)"
  official/mnist/mnist.py
  official/resnet/README.md
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_test.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/arg_parsers/parsers_test.py
  official/wide_deep/wide_deep.py
Labels: cla: yes

#4034 Benchmark update
  official/resnet/resnet_run_loop.py
  official/utils/logs/hooks_helper.py
  official/utils/logs/logger.py
  official/utils/logs/logger_test.py
  official/utils/logs/metric_hook.py
  official/utils/logs/metric_hook_test.py
Labels: cla: yes

#4022 Add Contribution and License in README
  README.md
Labels: cla: yes

#4040 Update the timestamp to default to UTC.
  official/utils/logs/logger.py
Labels: cla: yes

#2146 Removing unecessary clipping in preprocessor.py (fix #2066)
  research/object_detection/core/preprocessor.py
Labels: cla: yes

#4023 Research/minigo unit test
  research/minigo/README.md
  research/minigo/coords.py
  research/minigo/coords_test.py
  research/minigo/dualnet_test.py
  research/minigo/example_game.sgf
  research/minigo/features_test.py
  research/minigo/go.py
  research/minigo/go_test.py
  research/minigo/gtp_extensions.py
  research/minigo/gtp_wrapper.py
  research/minigo/mcts.py
  research/minigo/mcts_test.py
  research/minigo/preprocessing.py
  research/minigo/preprocessing_test.py
  research/minigo/sgf_wrapper.py
  research/minigo/sgf_wrapper_test.py
  research/minigo/strategies.py
  research/minigo/strategies_test.py
  research/minigo/symmetries_test.py
  research/minigo/utils_test.py
Labels: cla: yes

#4020 Replicate internal cluster changes in official mnist tpu example
  official/mnist/mnist_tpu.py
Labels: cla: yes

#4087 Add required packages which are missing for object detection
  research/setup.py
Labels: cla: yes

#4084 Fixed #4083 and two points of optimizations
  samples/cookbook/regression/automobile_data.py
  samples/cookbook/regression/custom_regression.py
  samples/cookbook/regression/dnn_regression.py
  samples/cookbook/regression/linear_regression.py
  samples/cookbook/regression/linear_regression_categorical.py
Labels: cla: yes

#4094 Update TensorRT unit for workspace size
  research/tensorrt/tensorrt.py
Labels: cla: yes

#4098 Fix 2 typos in eager.ipynb
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#4041 Add export savedmodel to wide_deep
  official/mnist/mnist.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/wide_deep/README.md
  official/wide_deep/wide_deep.py
Labels: cla: yes

#4092 Two new plot-generating scripts and changes in support of the ICLR poster.
  CODEOWNERS
  research/differential_privacy/pate/ICLR2018/README.md
  research/differential_privacy/pate/ICLR2018/generate_figures.sh
  research/differential_privacy/pate/ICLR2018/plot_partition.py
  research/differential_privacy/pate/ICLR2018/rdp_bucketized.py
  research/differential_privacy/pate/ICLR2018/rdp_cumulative.py
  research/differential_privacy/pate/ICLR2018/utility_queries_answered.py
  research/differential_privacy/pate/smooth_sensitivity.py
Labels: cla: yes

#4113 Minor update the resnet runloop.
  official/resnet/resnet_run_loop.py
Labels: cla: yes

#4123 Increase minimum TF version for DEFINE_enum and rename variable mappings for change to RNN variable names.
  research/maskgan/README.md
  research/maskgan/model_utils/variable_mapping.py
Labels: cla: yes

#4118 official/mnist: Add input_shape parameter to initial layer (#4104)
  official/mnist/mnist.py
Labels: cla: yes

#4110 Remove useless fields in resnet_model
  official/resnet/resnet_model.py
Labels: cla: yes

#4132 fix ResNet model call
  official/resnet/cifar10_main.py
  official/resnet/imagenet_main.py
Labels: cla: yes

#4133 Add new import paths to mnist_tpu.py
  official/mnist/mnist_tpu.py
Labels: cla: yes
