Repository tensorflow/models, pull requests merged in 2018-03, with the labels that each got.

#3371 Project import generated by Copybara. fixes #16593
  research/gan/cifar/eval.py
  research/gan/cifar/networks.py
  research/gan/cifar/util.py
  research/gan/image_compression/launch_jobs.sh
  research/gan/image_compression/networks_test.py
  research/gan/mnist/conditional_eval.py
  research/gan/mnist/eval.py
  research/gan/mnist/infogan_eval.py
  research/gan/mnist/networks.py
  research/gan/mnist/util.py
  research/gan/mnist_estimator/train.py
  research/gan/tutorial.ipynb
Labels: cla: yes

#3472 Multi-GPU Resnet
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_test.py
  official/resnet/resnet.py
  official/resnet/vgg_preprocessing.py
Labels: cla: yes

#3399 Adding dockerfiles that encapsulate this repository.
  official/Dockerfile.cpu
  official/Dockerfile.gpu
Labels: cla: yes

#3504 Jenkins, say Goodbye please.
  official/testing/docker_test.sh
  official/testing/test_models.sh
Labels: cla: yes

#3450 Updating tutorial URL
  tutorials/image/mnist/convolutional.py
Labels: cla: yes

#3509 Removing spaces
  official/Dockerfile.cpu
  official/Dockerfile.gpu
Labels: cla: yes

#3510 Upgrade mnist_tpu.py to use the new TPUClusterResolver.
  official/mnist/mnist_tpu.py
Labels: cla: yes

#3502 Support to set inter_op_parallelism_threads and intra_op_parallelism_threads for ResNet
  official/resnet/resnet.py
Labels: cla: yes

#2299 BUG: Fix inception imagenet download script
  research/inception/inception/data/download_imagenet.sh
  research/slim/datasets/download_imagenet.sh
Labels: cla: yes

#3518 Revert "Support to set inter_op_parallelism_threads and intra_op_para…
  official/resnet/resnet.py
Labels: cla: yes

#3322 Fix incompatible usage of 'filter' in Python3
  research/object_detection/utils/variables_helper.py
Labels: cla: yes

#3503 Add synthetic data option to Resnet
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_test.py
  official/resnet/resnet.py
  official/resnet/vgg_preprocessing.py
Labels: cla: yes

#3520 from six.moves import xrange (en masse) AGAIN
  research/adversarial_text/adversarial_losses.py
  research/adversarial_text/layers.py
  research/maskgan/generate_samples.py
  research/maskgan/model_utils/helper.py
  research/maskgan/model_utils/model_losses.py
  research/maskgan/model_utils/n_gram.py
  research/maskgan/models/critic_vd.py
  research/maskgan/models/feedforward.py
  research/maskgan/models/rnn.py
  research/maskgan/models/rnn_nas.py
  research/maskgan/models/rnn_vd.py
  research/maskgan/models/rnn_zaremba.py
  research/maskgan/models/rollout.py
  research/maskgan/models/seq2seq.py
  research/maskgan/models/seq2seq_nas.py
  research/maskgan/models/seq2seq_vd.py
  research/maskgan/models/seq2seq_zaremba.py
  research/maskgan/train_mask_gan.py
  research/slim/datasets/build_imagenet_data.py
  research/slim/datasets/preprocess_imagenet_validation_data.py
  research/slim/datasets/process_bounding_boxes.py
  research/slim/nets/cyclegan.py
  research/slim/nets/dcgan.py
  research/slim/nets/dcgan_test.py
Labels: cla: yes

#3533 Adding thread args back in, with allow_soft_placement
  official/resnet/resnet.py
Labels: cla: no

#3535 Update the eager MNIST example to use object-based checkpointing
  official/mnist/mnist_eager.py
  official/mnist/mnist_eager_test.py
Labels: cla: yes

#3534 Fix to Memory.query + other small changes in Learning to Remember Rare Events
  research/learning_to_remember_rare_events/data_utils.py
  research/learning_to_remember_rare_events/memory.py
  research/learning_to_remember_rare_events/model.py
  research/learning_to_remember_rare_events/train.py
Labels: cla: yes

#3521 Add deeplab model in tensorflow models
  CODEOWNERS
  research/deeplab/README.md
  research/deeplab/__init__.py
  research/deeplab/common.py
  research/deeplab/core/__init__.py
  research/deeplab/core/feature_extractor.py
  research/deeplab/core/preprocess_utils.py
  research/deeplab/core/preprocess_utils_test.py
  research/deeplab/core/xception.py
  research/deeplab/core/xception_test.py
  research/deeplab/datasets/__init__.py
  research/deeplab/datasets/build_cityscapes_data.py
  research/deeplab/datasets/build_data.py
  research/deeplab/datasets/build_voc2012_data.py
  research/deeplab/datasets/convert_cityscapes.sh
  research/deeplab/datasets/download_and_convert_voc2012.sh
  research/deeplab/datasets/remove_gt_colormap.py
  research/deeplab/datasets/segmentation_dataset.py
  research/deeplab/deeplab_demo.ipynb
  research/deeplab/eval.py
  research/deeplab/export_model.py
  research/deeplab/g3doc/cityscapes.md
  research/deeplab/g3doc/export_model.md
  research/deeplab/g3doc/faq.md
  research/deeplab/g3doc/img/image1.jpg
  research/deeplab/g3doc/img/image2.jpg
  research/deeplab/g3doc/img/image3.jpg
  research/deeplab/g3doc/img/image_info.txt
  research/deeplab/g3doc/img/vis1.png
  research/deeplab/g3doc/img/vis2.png
  research/deeplab/g3doc/img/vis3.png
  research/deeplab/g3doc/installation.md
  research/deeplab/g3doc/model_zoo.md
  research/deeplab/g3doc/pascal.md
  research/deeplab/input_preprocess.py
  research/deeplab/local_test.sh
  research/deeplab/model.py
  research/deeplab/model_test.py
  research/deeplab/train.py
  research/deeplab/utils/__init__.py
  research/deeplab/utils/get_dataset_colormap.py
  research/deeplab/utils/get_dataset_colormap_test.py
  research/deeplab/utils/input_generator.py
  research/deeplab/utils/save_annotation.py
  research/deeplab/utils/train_utils.py
  research/deeplab/vis.py
Labels: cla: yes

#3555 Small updates to astronet
  research/astronet/README.md
  research/astronet/astronet/data/generate_download_script.py
Labels: cla: yes

#3260 Fix a typo. Python function name
  samples/outreach/blogs/blog_estimators_dataset.py
Labels: cla: yes

#3561 unnecessary variable assignment in loop
  samples/core/get_started/premade_estimator.py
Labels: cla: yes

#3557 make /official a Python module
  official/README.md
  official/__init__.py
  official/mnist/mnist.py
  official/mnist/mnist_eager.py
  official/mnist/mnist_eager_test.py
  official/mnist/mnist_test.py
  official/mnist/mnist_tpu.py
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_test.py
  official/wide_deep/wide_deep_test.py
Labels: cla: yes

#3484 Allow the official resnet model to train as resnet_v1 and resnet_v2
  official/resnet/README.md
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_test.py
  official/resnet/resnet.py
  official/resnet/resnet_test.py
Labels: cla: yes

#3575 Fix import in resnet_test.py to use new module convention.
  official/resnet/resnet_test.py
Labels: cla: yes

#3551 adding deeplab in readme.md file under models/research
  research/README.md
Labels: cla: yes

#3580 Fix comment typos under models/research
  research/attention_ocr/python/inception_preprocessing.py
  research/inception/inception/image_processing.py
  research/slim/preprocessing/inception_preprocessing.py
  research/tcn/preprocessing.py
Labels: cla: yes

#3581 replace `FLAGS.batch_size` by `images.get_shape()[0]`
  tutorials/image/cifar10/cifar10.py
Labels: cla: yes

#3576 Update Dockerfile for GPU now that the branch has been merged
  official/Dockerfile.cpu
  official/Dockerfile.gpu
Labels: cla: yes

#3519 Add examples_per_second_hook and unit tests to the logging utils
  official/utils/__init__.py
  official/utils/logging/__init__.py
  official/utils/logging/hooks.py
  official/utils/logging/hooks_helper.py
  official/utils/logging/hooks_helper_test.py
  official/utils/logging/hooks_test.py
Labels: cla: yes

#3583 Pulling internal changes to github
  research/slim/BUILD
  research/slim/README.md
  research/slim/datasets/build_imagenet_data.py
  research/slim/datasets/download_imagenet.sh
  research/slim/datasets/preprocess_imagenet_validation_data.py
  research/slim/datasets/process_bounding_boxes.py
  research/slim/nets/cyclegan.py
  research/slim/nets/dcgan.py
  research/slim/nets/dcgan_test.py
  research/slim/nets/mobilenet/README.md
  research/slim/nets/mobilenet/__init__.py
  research/slim/nets/mobilenet/conv_blocks.py
  research/slim/nets/mobilenet/mobilenet.py
  research/slim/nets/mobilenet/mobilenet_v2.py
  research/slim/nets/mobilenet/mobilenet_v2_test.py
  research/slim/nets/mobilenet_v1.md
  research/slim/nets/mobilenet_v1.py
  research/slim/nets/mobilenet_v1_eval.py
  research/slim/nets/mobilenet_v1_train.py
  research/slim/nets/nasnet/nasnet_utils.py
  research/slim/nets/nets_factory.py
  research/slim/preprocessing/inception_preprocessing.py
Labels: cla: yes

#3558 More Preprocessing tuning for Resnet
  official/resnet/imagenet_main.py
  official/resnet/imagenet_preprocessing.py
  official/resnet/vgg_preprocessing.py
Labels: cla: yes

#3574 Unified arg parser
  official/__init__.py
  official/resnet/resnet.py
  official/utils/__init__.py
  official/utils/arg_parsers/__init__.py
  official/utils/arg_parsers/parsers.py
  official/utils/arg_parsers/parsers_test.py
Labels: cla: yes

#3597 restore --version flag in resnet parser
  official/resnet/resnet.py
Labels: cla: yes

#3599 Removing dependency on tf.test
  official/utils/logging/hooks_helper_test.py
Labels: cla: yes

#3585 Add data schema for the benchmark run in Bigquery.
  official/benchmark/datastore/schema/benchmark_metric.json
  official/benchmark/datastore/schema/benchmark_run.json
Labels: cla: yes

#3601 Making Running a header
  official/README.md
Labels: cla: yes

#3586 Update resnet with logging utils
  official/resnet/resnet.py
  official/utils/arg_parsers/parsers.py
  official/utils/arg_parsers/parsers_test.py
  official/utils/logging/hooks_helper.py
Labels: cla: yes

#3587 Fix typo in paper's arxiv.org url
  research/deeplab/model.py
Labels: cla: yes

#3602 Update dataset examples
  research/deeplab/g3doc/cityscapes.md
  research/deeplab/g3doc/pascal.md
Labels: cla: yes

#3604 remove duplicate flags
  research/deeplab/g3doc/cityscapes.md
  research/deeplab/g3doc/pascal.md
Labels: cla: yes

#3616 Remove unused master flag.
  official/mnist/mnist_tpu.py
Labels: cla: yes

#3620 plot shown in vis_segmentation
  research/deeplab/deeplab_demo.ipynb
Labels: cla: yes

#3621 Partition resnet code
  official/resnet/cifar10_main.py
  official/resnet/imagenet_main.py
  official/resnet/resnet_model.py
  official/resnet/resnet_run_loop.py
  official/resnet/resnet_test.py
Labels: cla: yes

#3623 Add pkulzc to object_detection owners.
  CODEOWNERS
Labels: cla: yes

#3598 Basic end to end test of resnet.
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_test.py
  official/resnet/resnet_model.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/testing/__init__.py
  official/utils/testing/integration.py
Labels: cla: yes, kokoro:force-run

#3630 Make TFGAN tutorial Python 3 compatible. Fixes issue #3413
  research/gan/tutorial.ipynb
Labels: cla: yes

#3634 fix doc of func `learning_rate_with_decay`
  official/resnet/resnet_run_loop.py
Labels: cla: yes

#3651 Improve directory treatment in ResNet end-to-end tests.
  official/resnet/cifar10_test.py
  official/resnet/imagenet_test.py
  official/utils/testing/integration.py
Labels: cla: yes

#3622 Python3 compatibility for AstroNet
  research/astronet/README.md
  research/astronet/astronet/astro_cnn_model/astro_cnn_model.py
  research/astronet/astronet/astro_fc_model/astro_fc_model.py
  research/astronet/astronet/data/generate_input_records.py
  research/astronet/astronet/ops/dataset_ops.py
  research/astronet/astronet/ops/input_ops.py
  research/astronet/astronet/ops/input_ops_test.py
  research/astronet/astronet/ops/testing.py
  research/astronet/astronet/util/config_util.py
  research/astronet/astronet/util/configdict.py
  research/astronet/astronet/util/estimator_util.py
  research/astronet/light_curve_util/kepler_io.py
  research/astronet/light_curve_util/util.py
  research/astronet/third_party/kepler_spline/kepler_spline.py
Labels: cla: yes

#3652 samples/java: Link to Fiji/ImageJ integration.
  samples/languages/java/README.md
Labels: cla: yes

#3650 Use util functions hooks_helper and parser in mnist and wide_deep
  official/mnist/README.md
  official/mnist/mnist.py
  official/mnist/mnist_eager.py
  official/resnet/cifar10_main.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/arg_parsers/parsers_test.py
  official/utils/logging/hooks_helper.py
  official/utils/testing/integration.py
  official/wide_deep/README.md
  official/wide_deep/wide_deep.py
Labels: cla: yes

#3654 Glint everything
  official/__init__.py
  official/mnist/dataset.py
  official/mnist/mnist.py
  official/mnist/mnist_eager.py
  official/mnist/mnist_eager_test.py
  official/mnist/mnist_test.py
  official/mnist/mnist_tpu.py
  official/resnet/cifar10_download_and_extract.py
  official/resnet/cifar10_main.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_main.py
  official/resnet/imagenet_preprocessing.py
  official/resnet/imagenet_test.py
  official/resnet/resnet_model.py
  official/resnet/resnet_run_loop.py
  official/utils/__init__.py
  official/utils/arg_parsers/parsers.py
  official/utils/logging/hooks_helper.py
  official/utils/logging/hooks_helper_test.py
  official/utils/logging/hooks_test.py
  official/utils/logging/logger.py
  official/utils/logging/logger_test.py
  official/utils/testing/integration.py
  official/utils/testing/pylint.rcfile
  official/wide_deep/data_download.py
  official/wide_deep/wide_deep.py
  official/wide_deep/wide_deep_test.py
Labels: cla: yes

#3653 ResNet argparse fixes.
  official/resnet/cifar10_main.py
  official/resnet/imagenet_main.py
Labels: cla: yes

#3675 Use reduce_mean instead of Average Pooling in Resnet
  official/resnet/imagenet_test.py
  official/resnet/resnet_model.py
Labels: cla: yes

#3676 A few linting fixes
  official/utils/testing/pylint.rcfile
Labels: cla: yes

#3645 Update running_pets instructions to link to running locally.
  research/object_detection/g3doc/running_pets.md
Labels: cla: yes

#3685 delete resnet_test.py, as it is numerically unstable.
  official/resnet/resnet_test.py
Labels: cla: yes

#3672 Add session hook for benchmark metric logging.
  official/utils/logging/metric_hook.py
  official/utils/logging/metric_hook_test.py
Labels: cla: yes

#3692 fix bugs in Python 3.X
  research/pcl_rl/env_spec.py
Labels: cla: yes

#3702 from six.moves import xrange (en masse) YET AGAIN
  research/lexnet_nc/lexnet_model.py
  research/slim/datasets/build_imagenet_data.py
  research/slim/datasets/preprocess_imagenet_validation_data.py
  research/slim/datasets/process_bounding_boxes.py
  research/slim/nets/cyclegan.py
  research/slim/nets/dcgan.py
  research/slim/nets/dcgan_test.py
  research/swivel/glove_to_shards.py
Labels: cla: yes

#3694 Add a tf.summary.scalar call for L2 loss in resnet
  official/resnet/resnet_run_loop.py
Labels: cla: yes

#3691 Updated README run instructions
  official/mnist/README.md
  official/resnet/README.md
  official/wide_deep/README.md
Labels: cla: yes

#3693 Update comment on folder structure
  research/deeplab/datasets/download_and_convert_voc2012.sh
Labels: cla: yes

#3686 Fix DeprecationWarning
  research/deeplab/model_test.py
Labels: cla: yes

#3709 Add mobilenetv2 support in deeplab
  research/deeplab/README.md
  research/deeplab/common.py
  research/deeplab/core/feature_extractor.py
  research/deeplab/datasets/convert_cityscapes.sh
  research/deeplab/datasets/download_and_convert_voc2012.sh
  research/deeplab/deeplab_demo.ipynb
  research/deeplab/eval.py
  research/deeplab/g3doc/cityscapes.md
  research/deeplab/g3doc/faq.md
  research/deeplab/g3doc/model_zoo.md
  research/deeplab/g3doc/pascal.md
  research/deeplab/local_test_mobilenetv2.sh
  research/deeplab/model.py
  research/deeplab/model_test.py
  research/deeplab/train.py
  research/deeplab/vis.py
Labels: cla: yes

#3669 syntax error : download_and_convert_VOC2012.sh
  research/deeplab/datasets/download_and_convert_voc2012.sh
Labels: cla: yes

#3684 Arg parsing cleanup for MNIST and Wide-Deep
  official/mnist/mnist.py
  official/mnist/mnist_eager.py
  official/wide_deep/wide_deep.py
Labels: cla: yes

#3707 Add PNASNet model.
  research/slim/BUILD
  research/slim/README.md
  research/slim/nets/nasnet/pnasnet.py
  research/slim/nets/nasnet/pnasnet_test.py
  research/slim/nets/nets_factory.py
  research/slim/preprocessing/preprocessing_factory.py
Labels: cla: yes

#3704 Resnet benchmark logging
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/arg_parsers/parsers_test.py
  official/utils/logging/hooks_helper.py
  official/utils/logging/hooks_helper_test.py
  official/utils/logging/logger.py
  official/utils/logging/logger_test.py
Labels: cla: yes

#3725 Fix random order problem in benchmark logging.
  official/utils/logging/logger.py
  official/utils/logging/logger_test.py
Labels: cla: yes

#3756 deeplab_demo notebook py2 and py3 support
  research/deeplab/deeplab_demo.ipynb
Labels: cla: yes

#3758 Fix typo.
  research/deeplab/train.py
Labels: cla: yes

#3708 Benchmark run info logging
  official/utils/logging/logger.py
  official/utils/logging/logger_test.py
Labels: cla: yes

#3679 Update Installation.md
  research/object_detection/g3doc/installation.md
Labels: cla: yes

#3760 Add requirements.txt to official.
  official/README.md
  official/requirements.txt
  official/utils/logging/logger.py
Labels: cla: yes

#3777 Bug fix on flag name in wide_deep.py
  official/wide_deep/wide_deep.py
Labels: cla: yes

#3723 Add golden tests to official.
  official/resnet/layer_test.py
  official/utils/testing/reference_data.py
  official/utils/testing/reference_data/reference_data_test/dense/expected_graph
  official/utils/testing/reference_data/reference_data_test/dense/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/reference_data_test/dense/model.ckpt.index
  official/utils/testing/reference_data/reference_data_test/dense/results.json
  official/utils/testing/reference_data/reference_data_test/dense/tf_version.json
  official/utils/testing/reference_data/reference_data_test/uniform_random/expected_graph
  official/utils/testing/reference_data/reference_data_test/uniform_random/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/reference_data_test/uniform_random/model.ckpt.index
  official/utils/testing/reference_data/reference_data_test/uniform_random/results.json
  official/utils/testing/reference_data/reference_data_test/uniform_random/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_projection_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_bottleneck_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_projection_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-1_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/expected_graph
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/results.json
  official/utils/testing/reference_data/resnet/batch-size-32_building_version-2_width-8_channels-4/tf_version.json
  official/utils/testing/reference_data/resnet/batch_norm/expected_graph
  official/utils/testing/reference_data/resnet/batch_norm/model.ckpt.data-00000-of-00001
  official/utils/testing/reference_data/resnet/batch_norm/model.ckpt.index
  official/utils/testing/reference_data/resnet/batch_norm/results.json
  official/utils/testing/reference_data/resnet/batch_norm/tf_version.json
  official/utils/testing/reference_data_test.py
Labels: cla: yes

#3782 (Lint) Fix line with too many characters
  official/wide_deep/wide_deep.py
Labels: cla: yes

#3781 Update the importing logic for cpuinfo and psutil.
  official/utils/logging/logger.py
Labels: cla: yes

#3776 Add benchmark upload util to Bigquery.
  official/benchmark/datastore/schema/benchmark_run.json
  official/requirements.txt
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/arg_parsers/parsers_test.py
  official/utils/logging/benchmark_uploader.py
  official/utils/logging/logger.py
  official/utils/logging/logger_test.py
  official/utils/testing/pylint.rcfile
Labels: cla: yes

#3759 Add SavedModel export to Resnet
  official/mnist/mnist.py
  official/resnet/cifar10_main.py
  official/resnet/imagenet_main.py
  official/resnet/resnet_run_loop.py
  official/utils/arg_parsers/parsers.py
  official/utils/export/__init__.py
  official/utils/export/export.py
  official/utils/export/export_test.py
Labels: cla: yes

#3798 Add End-to-end tests for wide deep, and fix "wide" and "deep" configurations.
  official/utils/testing/integration.py
  official/wide_deep/wide_deep.py
  official/wide_deep/wide_deep_test.py
Labels: cla: yes

#3807 Add eager execution demo.
  samples/outreach/demos/eager_execution.ipynb
Labels: cla: yes

#3811 Fix autograph link in eager execution demo.
  samples/outreach/demos/eager_execution.ipynb
Labels: cla: yes

#3812 Docs: Adds eager notebook to the getting started samples
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#3810 fixed dimension compatibility issue for numpy
  tutorials/image/cifar10/cifar10.py
Labels: cla: yes

#3814 Fix links that use nested elements.
  samples/core/get_started/eager.ipynb
  samples/outreach/demos/eager_execution.ipynb
Labels: cla: yes

#3815 Eager colab: make the "not like numpy" statement slightly more useful.
  samples/outreach/demos/eager_execution.ipynb
Labels: cla: yes

#3808 Adding scripts for TensorRT
  research/tensorrt/README.md
  research/tensorrt/image.jpg
  research/tensorrt/labellist.json
  research/tensorrt/tensorrt.py
Labels: cla: yes

#3816 Update title to match other beginner guides.
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#3817 Remove code formatted links that don't render in correctly.
  samples/core/get_started/eager.ipynb
Labels: cla: yes

#3766 vis.py: use basename of image when saving raw annotations to prevent file-not-found error
  research/deeplab/vis.py
Labels: cla: yes

#3821 Fix so images render on github.
  samples/core/get_started/eager.ipynb
Labels: cla: yes
