Repository tensorflow/models, pull requests merged in 2019-07, with the labels that each got.

#7135 Allow distibution_utils.py to work with PSStrategy or none strategy
  official/utils/misc/distribution_utils.py
Labels: cla: yes

#7134 Add StepCounterHook to hooks_helper.py
  official/utils/logs/hooks_helper.py
Labels: cla: yes

#7141 Merged commit includes the following changes:
  official/bert/benchmark/bert_squad_benchmark.py
  official/bert/common_flags.py
  official/bert/run_classifier.py
  official/bert/run_pretraining.py
  official/bert/run_squad.py
Labels: cla: yes

#7101 Unit tests pass TF 2.0 GPU and CPU locally.
  official/benchmark/benchmark_uploader.py
  official/benchmark/benchmark_uploader_test.py
  official/boosted_trees/train_higgs_test.py
  official/mnist/mnist_eager.py
  official/mnist/mnist_eager_test.py
  official/mnist/mnist_test.py
  official/recommendation/data_test.py
  official/recommendation/ncf_test.py
  official/resnet/cifar10_test.py
  official/resnet/imagenet_test.py
  official/resnet/keras/keras_common_test.py
  official/resnet/keras/keras_imagenet_test.py
  official/resnet/layer_test.py
  official/transformer/compute_bleu_test.py
  official/transformer/model/beam_search_test.py
  official/transformer/model/model_utils_test.py
  official/transformer/utils/tokenizer_test.py
  official/transformer/v2/transformer_main_test.py
  official/utils/data/file_io_test.py
  official/utils/logs/hooks_helper_test.py
  official/utils/logs/logger.py
  official/utils/logs/logger_test.py
  official/utils/misc/model_helpers_test.py
  official/utils/testing/reference_data.py
  official/utils/testing/reference_data_test.py
  official/utils/testing/scripts/presubmit.sh
  official/wide_deep/census_test.py
  official/wide_deep/movielens_dataset.py
  official/wide_deep/movielens_test.py
Labels: cla: yes

#7160 Update download_and_convert_ade20k.sh
  research/deeplab/datasets/download_and_convert_ade20k.sh
Labels: cla: yes

#7157 specify the 'num_gpus' argument
  research/deep_speech/deep_speech.py
Labels: cla: yes

#6928 Bug fix of cifar10_eval.py
  tutorials/image/cifar10/cifar10_eval.py
Labels: cla: yes

#7168 Reduce iterations from 20 to 12 and add FP16 dynamic.
  official/recommendation/ncf_keras_main.py
  official/transformer/v2/transformer_benchmark.py
Labels: cla: yes

#7169 Reorder tests and add CTL XLA tests.
  official/recommendation/ncf_keras_benchmark.py
Labels: cla: yes

#7177 Update adversarial_crypto to tf 1.14 syntax, fix bug #7125
  research/adversarial_crypto/train_eval.py
Labels: cla: yes

#7178 Improve performance for Cifar ResNet benchmarks
  official/resnet/keras/keras_cifar_main.py
  official/resnet/keras/resnet_cifar_model.py
Labels: cla: yes

#7154 Update readme.md to fix the issue #7040.
  research/maskgan/README.md
Labels: cla: no

#7186 Move Keras Hook to use global step to resolve issues across epochs.
  official/resnet/keras/keras_cifar_benchmark.py
  official/utils/misc/keras_utils.py
Labels: cla: yes

#7191 Creates a Transformer V2 ReadMe
  official/transformer/README.md
  official/transformer/v2/README.md
Labels: cla: yes

#7189 ResNet50 and ResNet56 Add stdev to the Dense layer.
  official/resnet/keras/resnet_cifar_model.py
  official/resnet/keras/resnet_model.py
Labels: cla: yes

#7196 Record highest uncased bleu found.
  official/transformer/v2/transformer_benchmark.py
  official/transformer/v2/transformer_main.py
Labels: cla: yes

#7183 Reduce transformer fp16 test to 12 iterations.
  official/transformer/v2/transformer_benchmark.py
Labels: cla: yes

#7209 Merged commit includes the following changes: Adds tf.summary for bert training
  official/bert/model_training_utils.py
Labels: cla: yes, kokoro:force-run

#7218 Initial implementation of Shakespeare character LSTM.
  official/staging/shakespeare/README.md
  official/staging/shakespeare/shakespeare_main.py
Labels: cla: yes

#7220 Merged commit includes the following changes:
  research/lstm_object_detection/README.md
  research/lstm_object_detection/configs/lstm_ssd_mobilenet_v1_imagenet.config
  research/lstm_object_detection/lstm/lstm_cells.py
  research/lstm_object_detection/meta_architectures/lstm_ssd_meta_arch.py
  research/lstm_object_detection/models/lstm_ssd_interleaved_mobilenet_v2_feature_extractor_test.py
  research/lstm_object_detection/tflite/BUILD
  research/lstm_object_detection/tflite/WORKSPACE
  research/lstm_object_detection/tflite/mobile_lstd_tflite_client.cc
  research/lstm_object_detection/tflite/mobile_lstd_tflite_client.h
  research/lstm_object_detection/tflite/mobile_ssd_client.cc
  research/lstm_object_detection/tflite/mobile_ssd_client.h
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.cc
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.h
  research/lstm_object_detection/tflite/protos/BUILD
  research/lstm_object_detection/tflite/protos/anchor_generation_options.proto
  research/lstm_object_detection/tflite/protos/box_encodings.proto
  research/lstm_object_detection/tflite/protos/detections.proto
  research/lstm_object_detection/tflite/protos/labelmap.proto
  research/lstm_object_detection/tflite/protos/mobile_ssd_client_options.proto
  research/lstm_object_detection/tflite/protos/proto_config.asciipb
  research/lstm_object_detection/tflite/utils/BUILD
  research/lstm_object_detection/tflite/utils/conversion_utils.cc
  research/lstm_object_detection/tflite/utils/conversion_utils.h
  research/lstm_object_detection/tflite/utils/conversion_utils_test.cc
  research/lstm_object_detection/tflite/utils/file_utils.cc
  research/lstm_object_detection/tflite/utils/file_utils.h
  research/lstm_object_detection/tflite/utils/ssd_utils.cc
  research/lstm_object_detection/tflite/utils/ssd_utils.h
Labels: cla: yes

#7206 Ncf perf optimizations for CTL and multi GPU
  official/recommendation/ncf_keras_main.py
Labels: cla: yes

#7221 Adds run_eagerly option for bert training utils
  official/bert/model_training_utils.py
Labels: cla: yes

#7227 Fix for #7225: CIFAR-10 eval fails with error TypeError: Input 'predictions' of 'InTopKV2' Op has type float16 that contributed by mattmann.
  tutorials/image/cifar10/cifar10_eval.py
Labels: cla: yes

#7248 Refactor and add benchmarks as well as accuracy tests for GPU and CPU
  official/staging/shakespeare/shakespeare_benchmark.py
  official/staging/shakespeare/shakespeare_main.py
  official/utils/misc/keras_utils.py
Labels: cla: yes

#7251 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#7252 Merged commit includes the following changes:
  official/bert/optimization.py
  official/bert/run_squad.py
Labels: cla: yes

#7255 Merged commit includes the following changes:
  official/bert/optimization.py
  official/staging/shakespeare/README.md
Labels: cla: yes

#7254 Change how TF 2 is checked
  official/utils/misc/keras_utils.py
Labels: cla: yes

#7217 Fix for TF-models #7216: CIFAR-10 tutorial for multi-GPU fails becaus…
  tutorials/image/cifar10/cifar10_multi_gpu_train.py
Labels: cla: yes

#7260 Revert "Change how TF 2 is checked"
  official/utils/misc/keras_utils.py
Labels: cla: yes

#7263 Merged commit includes the following changes:
  official/bert/model_training_utils.py
  official/modeling/__init__.py
  official/nlp/__init__.py
  official/r1/__init__.py
  official/resnet/keras/keras_imagenet_main.py
  official/staging/__init__.py
  official/staging/shakespeare/__init__.py
  official/vision/__init__.py
Labels: cla: yes

#7264 Merged commit includes the following changes:
  official/resnet/keras/keras_common.py
  official/resnet/keras/keras_imagenet_benchmark.py
Labels: cla: yes

#7205 [Transformer] Use float16 input and output for softmax in mixed-precision training
  official/transformer/v2/attention_layer.py
Labels: cla: yes

#7268 Add a simple signal-based Python callstack sampler for debugging
  official/utils/misc/callstack_sampler.py
Labels: cla: yes

#7265 Add a new sanity check script that is able to only check incremental changes.
  official/utils/testing/pylint.rcfile
  official/utils/testing/scripts/builds_common.sh
  official/utils/testing/scripts/ci_sanity.sh
Labels: cla: yes, models: official

#7277 Merged commit includes the following changes:
  official/bert/benchmark/benchmark_utils.py
  official/bert/model_saving_utils.py
  official/bert/run_classifier.py
  official/bert/run_pretraining.py
Labels: cla: yes, kokoro:run

#7278 Update lint presubmit to be consistent with tensorflow
  official/utils/testing/scripts/ci_sanity.sh
Labels: cla: yes

#7281 Merged commit includes the following changes:
  official/recommendation/create_ncf_data.py
  official/recommendation/data_pipeline.py
  official/recommendation/data_preprocessing.py
  official/recommendation/data_test.py
  official/recommendation/ncf_common.py
Labels: cla: yes

#7274 add log_steps with faster logging for 8xGPU.
  official/staging/shakespeare/shakespeare_benchmark.py
  official/staging/shakespeare/shakespeare_main.py
Labels: cla: yes

#7276 Single execution path tests for ResNet50, ResNet56, NCF, and Shakespeare LSTM.
  official/recommendation/ncf_common.py
  official/recommendation/ncf_keras_benchmark.py
  official/recommendation/ncf_keras_main.py
  official/resnet/keras/keras_cifar_benchmark.py
  official/resnet/keras/keras_cifar_main.py
  official/resnet/keras/keras_common.py
  official/resnet/keras/keras_imagenet_benchmark.py
  official/resnet/keras/keras_imagenet_main.py
  official/staging/shakespeare/shakespeare_benchmark.py
  official/staging/shakespeare/shakespeare_main.py
  official/transformer/v2/misc.py
  official/utils/flags/_performance.py
Labels: cla: yes

#7289 Merged commit includes the following changes:
  official/bert/README.md
  official/bert/model_training_utils.py
Labels: cla: yes

#7285 Lower MLPerf hr@10 target
  official/recommendation/ncf_keras_benchmark.py
Labels: cla: yes

#7287 Fix Resnet50 test flags to force_v2_in_keras_compile
  official/resnet/keras/keras_imagenet_benchmark.py
Labels: cla: yes

#7291 NCF benchmark: top_1 to hr_at_10_max.
  official/recommendation/ncf_keras_benchmark.py
Labels: cla: yes

#7294 Don't return anything in main function
  official/resnet/keras/keras_imagenet_main.py
Labels: cla: yes

#7296 Shakespeare: Additional force_v2 tests.
  official/staging/shakespeare/shakespeare_benchmark.py
Labels: cla: yes

#7295 Add a high max for MLPerf tests so they are green.
  official/recommendation/ncf_keras_benchmark.py
Labels: cla: yes

#7298 Merged commit includes the following changes:
  official/bert/bert_models.py
Labels: cla: yes

#7301 Merged commit includes the following changes:
  official/bert/benchmark/bert_benchmark.py
  official/bert/benchmark/bert_squad_benchmark.py
  official/bert/model_training_utils.py
  official/bert/run_squad.py
Labels: cla: yes

#7302 Add Resnet50 CTL benchmark (pure eager w/ distribution strategy)
  official/resnet/ctl/ctl_imagenet_benchmark.py
Labels: cla: yes

#7307 Merged commit includes the following changes:
  official/bert/run_squad.py
Labels: cla: yes, kokoro:run, models: official

#7309 Merged commit includes the following changes:
  official/bert/benchmark/bert_squad_benchmark.py
  official/bert/bert_models.py
  official/bert/common_flags.py
  official/bert/model_training_utils.py
  official/bert/modeling.py
  official/bert/run_squad.py
Labels: cla: yes

#7322 Merged commit includes the following changes:
  official/recommendation/create_ncf_data.py
  official/recommendation/data_pipeline.py
  official/recommendation/ncf_common.py
  official/recommendation/ncf_input_pipeline.py
  official/recommendation/ncf_keras_benchmark.py
  official/recommendation/ncf_keras_main.py
Labels: cla: yes

#7323 Merged commit includes the following changes:
  official/bert/model_saving_utils.py
Labels: cla: yes

#7324 Merged commit includes the following changes:
  official/bert/modeling.py
Labels: cla: yes

#7325 Merged commit includes the following changes:
  official/recommendation/ncf_keras_main.py
Labels: cla: yes

#6555 Support for non-TYPE_3BYTE_BGR images in Java project
  samples/languages/java/object_detection/src/main/java/DetectObjects.java
Labels: cla: yes

#5895 Use distutils.version.StrictVersion for version comparisons
  samples/outreach/blogs/blog_custom_estimators.py
  samples/outreach/blogs/blog_estimators_dataset.py
  tutorials/rnn/ptb/ptb_word_lm.py
Labels: cla: yes

#7335 Remove make_one_shot_iterator
  samples/cookbook/regression/automobile_data.py
Labels: cla: yes

#7333 Add accuracy and performance Resnet runs with --force_v2_in_keras_com…
  official/resnet/keras/keras_imagenet_benchmark.py
Labels: cla: yes

#7334 Add 8 GPUs force_v2_in_keras_compile runs for NCF.
  official/recommendation/ncf_keras_benchmark.py
Labels: cla: yes

#7344 Change to experimental_run_tf_function.
  official/recommendation/ncf_keras_main.py
  official/resnet/keras/keras_cifar_main.py
  official/resnet/keras/keras_imagenet_main.py
  official/staging/shakespeare/shakespeare_main.py
Labels: cla: yes

#7346 Merged commit includes the following changes:
  official/recommendation/data_pipeline.py
  official/recommendation/ncf_keras_main.py
Labels: cla: yes
