Repository tensorflow/models, pull requests merged in 2019-08, with the labels that each got.

#7347 Merged commit includes the following changes:
  official/bert/input_pipeline.py
  official/bert/run_pretraining.py
Labels: cla: yes

#7353 Remove whitespaces from empty lines
  official/recommendation/ncf_keras_benchmark.py
  official/resnet/keras/keras_imagenet_benchmark.py
Labels: cla: yes

#7354 Merged commit includes the following changes:
  official/bert/modeling.py
  official/bert/optimization.py
  official/resnet/keras/keras_imagenet_main.py
  official/transformer/v2/beam_search.py
  official/utils/logs/logger_test.py
Labels: cla: yes

#7355 Move the official ResNet (estimator version) under `official/r1`
  official/r1/resnet/README.md
  official/r1/resnet/__init__.py
  official/r1/resnet/cifar10_download_and_extract.py
  official/r1/resnet/cifar10_main.py
  official/r1/resnet/cifar10_test.py
  official/r1/resnet/estimator_benchmark.py
  official/r1/resnet/imagenet_main.py
  official/r1/resnet/imagenet_preprocessing.py
  official/r1/resnet/imagenet_test.py
  official/r1/resnet/layer_test.py
  official/r1/resnet/resnet_model.py
  official/r1/resnet/resnet_run_loop.py
  official/resnet/README.md
  official/resnet/__init__.py
Labels: cla: yes

#7357 Merged commit includes the following changes:
  official/bert/benchmark/bert_benchmark.py
  official/bert/benchmark/bert_squad_benchmark.py
  official/bert/common_flags.py
  official/bert/run_classifier.py
  official/bert/run_squad.py
Labels: cla: yes

#7358 Merged commit includes the following changes:
  research/lstm_object_detection/tflite/BUILD
  research/lstm_object_detection/tflite/WORKSPACE
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.cc
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.h
  research/lstm_object_detection/tflite/protos/mobile_ssd_client_options.proto
Labels: cla: yes

#7365 Merged commit includes the following changes:
  official/bert/modeling.py
  official/resnet/keras/cifar_preprocessing.py
  official/resnet/keras/imagenet_preprocessing.py
  official/resnet/keras/keras_cifar_benchmark.py
  official/resnet/keras/keras_cifar_main.py
  official/resnet/keras/keras_cifar_test.py
  official/resnet/keras/keras_imagenet_main.py
  official/resnet/keras/keras_imagenet_test.py
Labels: cla: yes

#7366 Update presubmit.sh
  official/utils/testing/scripts/presubmit.sh
Labels: cla: yes

#7367 Update to use py3 lint
  official/utils/testing/scripts/ci_sanity.sh
Labels: cla: yes

#7368 Merged commit includes the following changes:
  official/resnet/ctl/ctl_common.py
  official/resnet/ctl/ctl_imagenet_benchmark.py
  official/resnet/ctl/ctl_imagenet_main.py
  official/resnet/ctl/ctl_imagenet_test.py
Labels: cla: yes

#7370 add an encoder mode for BertModel which returns all layers.
  official/bert/modeling.py
Labels: cla: yes

#7382 Fix the ValueError: Error when checking model input on the new codepath
  official/transformer/v2/transformer_main.py
Labels: cla: yes

#7359 Remove layout off tests and related utils.
  official/resnet/keras/keras_cifar_main.py
  official/resnet/keras/keras_common.py
  official/resnet/keras/keras_imagenet_benchmark.py
  official/resnet/keras/keras_imagenet_main.py
  official/utils/misc/keras_utils.py
Labels: cla: yes

#7303 Force GPU placement for Resnet pure eager benchmark
  official/resnet/keras/keras_imagenet_benchmark.py
Labels: cla: yes

#7384 [Transformer] Remove turning off grappler layout optimizer
  official/transformer/v2/transformer_main.py
Labels: cla: yes

#7383 [ResNet / NCF] Test force V1 path and allow V2 path as default
  official/recommendation/ncf_keras_benchmark.py
  official/recommendation/ncf_keras_main.py
  official/resnet/keras/keras_cifar_benchmark.py
  official/resnet/keras/keras_cifar_main.py
  official/resnet/keras/keras_imagenet_benchmark.py
  official/resnet/keras/keras_imagenet_main.py
  official/utils/flags/_performance.py
Labels: cla: yes

#7385 Merged commit includes the following changes:
  official/bert/model_training_utils.py
Labels: cla: yes

#7391 Add non-CuDNN LSTM option and PerfZero benchmarks.
  official/staging/shakespeare/shakespeare_benchmark.py
  official/staging/shakespeare/shakespeare_main.py
Labels: cla: yes

#7393 Merged commit includes the following changes:
  official/bert/optimization.py
  official/modeling/hyperparams/params_dict.py
  official/modeling/hyperparams/params_dict_test.py
Labels: cla: yes

#7394 Create __init__.py
  official/modeling/hyperparams/__init__.py
Labels: cla: yes, kokoro:force-run

#7390 [ResNet56] Metric fixed back to categorical_accuracy.
  official/resnet/keras/keras_cifar_main.py
Labels: cla: yes

#7398 Use Adam instead of LazyAdam: _resource_apply_sparse() has never been called
  official/modeling/hyperparams/__init__.py
  official/transformer/v2/optimizer.py
  official/transformer/v2/transformer_main.py
Labels: cla: yes

#7405 Fix 8 GPU non-CuDNN LSTM tests.
  official/staging/shakespeare/shakespeare_benchmark.py
Labels: cla: yes

#7404 We should call training=True in CTL train step.
  official/bert/benchmark/bert_squad_benchmark.py
  official/bert/common_flags.py
  official/bert/model_training_utils.py
  official/bert/run_classifier.py
Labels: cla: yes

#7402 Fix fp16 Transformer model.
  official/transformer/model/beam_search.py
  official/transformer/v2/beam_search.py
  official/transformer/v2/embedding_layer.py
  official/transformer/v2/transformer.py
  official/transformer/v2/transformer_main_test.py
Labels: cla: yes

#7229 [NCF] Add run_eagerly for ctl.
  official/recommendation/ncf_keras_benchmark.py
  official/recommendation/ncf_keras_main.py
Labels: cla: yes

#7429 Add a public method to extract shareable layers with decoder.
  official/bert/benchmark/bert_squad_benchmark.py
  official/bert/modeling.py
  official/bert/run_classifier.py
  official/bert/run_pretraining.py
  official/bert/run_squad.py
  official/utils/misc/tpu_lib.py
Labels: cla: yes

#7430 Merged commit includes the following changes:
  official/recommendation/data_pipeline.py
  official/recommendation/data_test.py
  official/recommendation/ncf_common.py
  official/recommendation/ncf_estimator_main.py
  official/recommendation/ncf_input_pipeline.py
  official/recommendation/ncf_keras_main.py
  official/recommendation/ncf_test.py
  official/recommendation/neumf_model.py
  official/utils/misc/distribution_utils.py
  official/utils/misc/tpu_lib.py
Labels: cla: yes

#7379 Lstm object detection improvements
  research/lstm_object_detection/README.md
  research/lstm_object_detection/configs/lstm_ssd_interleaved_mobilenet_v2_imagenet.config
  research/lstm_object_detection/eval.py
  research/lstm_object_detection/export_tflite_lstd_graph.py
  research/lstm_object_detection/export_tflite_lstd_graph_lib.py
  research/lstm_object_detection/export_tflite_lstd_model.py
  research/lstm_object_detection/g3doc/exporting_models.md
  research/lstm_object_detection/inputs/seq_dataset_builder_test.py
  research/lstm_object_detection/test_tflite_model.py
  research/lstm_object_detection/utils/config_util.py
Labels: cla: yes

#7431 Merged commit includes the following changes:
  official/bert/benchmark/bert_squad_benchmark.py
Labels: cla: yes

#7435 Remove 8xGPU XLA tests. They are not supported yet.
  official/recommendation/ncf_keras_benchmark.py
Labels: cla: yes

#7437 [ResNet] Removed tests no longer closely monitored.
  official/resnet/keras/keras_imagenet_benchmark.py
Labels: cla: yes, ready to pull

#7441 Fixed typo with EdgeTPU header, in copybara config.
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.h
Labels: cla: yes

#7439 [Shakespeare LSTM] Remove XLA 8xGPU test.
  official/staging/shakespeare/shakespeare_benchmark.py
Labels: cla: yes, ready to pull

#7460 Fix a typo in the included header file name
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.h
Labels: cla: yes

#7462 Show flags when --help is specified in resnet.
  official/resnet/ctl/ctl_imagenet_main.py
  official/resnet/keras/keras_imagenet_main.py
Labels: cla: yes, ready to pull

#7470 Merged commit includes the following changes:
  research/lstm_object_detection/export_tflite_lstd_graph.py
  research/lstm_object_detection/export_tflite_lstd_graph_lib.py
  research/lstm_object_detection/export_tflite_lstd_model.py
  research/lstm_object_detection/g3doc/exporting_models.md
  research/lstm_object_detection/test_tflite_model.py
  research/lstm_object_detection/tflite/BUILD
  research/lstm_object_detection/tflite/mobile_lstd_tflite_client.cc
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.h
Labels: cla: yes

#7472 Remove stale code
  research/lstm_object_detection/tflite/WORKSPACE
Labels: cla: yes

#7492 Resubmitting changes which have been reverted.
  research/lstm_object_detection/export_tflite_lstd_graph.py
  research/lstm_object_detection/export_tflite_lstd_graph_lib.py
  research/lstm_object_detection/export_tflite_lstd_model.py
  research/lstm_object_detection/g3doc/exporting_models.md
  research/lstm_object_detection/test_tflite_model.py
  research/lstm_object_detection/tflite/BUILD
  research/lstm_object_detection/tflite/WORKSPACE
  research/lstm_object_detection/tflite/mobile_lstd_tflite_client.cc
  research/lstm_object_detection/tflite/mobile_ssd_tflite_client.h
Labels: cla: yes
