Repository tensorflow/models, pull requests merged in 2020-07, with the labels that each got.

#8760 TF2 version for global feature model exporting
  research/delf/delf/python/training/README.md
  research/delf/delf/python/training/model/export_global_model.py
  research/delf/delf/python/training/model/export_model_utils.py
Labels: cla: yes

#8761 Merged commit includes the following changes:
  research/object_detection/builders/decoder_builder.py
  research/object_detection/inputs.py
  research/object_detection/inputs_test.py
  research/object_detection/meta_architectures/ssd_meta_arch.py
Labels: cla: yes

#8762 Remove extraneous spaces in FasterRCNN Resnet keras fpn feature extractor
  research/object_detection/models/faster_rcnn_resnet_v1_fpn_keras_feature_extractor.py
Labels: cla: yes

#8767 DELF documentation updates
  research/delf/INSTALL_INSTRUCTIONS.md
  research/delf/README.md
  research/delf/delf/python/training/README.md
  research/delf/setup.py
Labels: cla: yes

#8779 Merged commit includes the following changes:
  research/object_detection/builders/model_builder.py
  research/object_detection/core/target_assigner.py
  research/object_detection/core/target_assigner_test.py
  research/object_detection/dataset_tools/context_rcnn/add_context_to_examples.py
  research/object_detection/dataset_tools/context_rcnn/create_cococameratraps_tfexample_main.py
  research/object_detection/dataset_tools/context_rcnn/generate_detection_data.py
  research/object_detection/dataset_tools/context_rcnn/generate_embedding_data.py
  research/object_detection/meta_architectures/faster_rcnn_meta_arch.py
  research/object_detection/models/faster_rcnn_resnet_v1_fpn_keras_feature_extractor.py
  research/object_detection/models/faster_rcnn_resnet_v1_fpn_keras_feature_extractor_tf2_test.py
Labels: cla: yes

#8757 attention_ocr: added export for SavedModel format.
  research/attention_ocr/README.md
  research/attention_ocr/python/common_flags.py
  research/attention_ocr/python/data_provider.py
  research/attention_ocr/python/datasets/fsns.py
  research/attention_ocr/python/model.py
  research/attention_ocr/python/model_export.py
  research/attention_ocr/python/model_export_lib.py
  research/attention_ocr/python/model_export_test.py
  research/attention_ocr/python/model_test.py
  research/attention_ocr/python/sequence_layers.py
  research/attention_ocr/python/utils.py
Labels: cla: yes, stat:awaiting review

#8799 add readme and example notebook
  research/mobilenet/README.md
  research/mobilenet/configs/archs.py
  research/mobilenet/mobilenet_trainer.py
  research/mobilenet/notebooks/MNV1_Migrate_TF1_to_TF2_Keras.ipynb
  research/mobilenet/tf1_loader/mobilenet_evaluator.py
Labels: cla: yes, help wanted:paper implementation

#8766 Fix typo in retinanet_model.py
  official/vision/detection/modeling/retinanet_model.py
Labels: cla: yes, ready to pull

#8803 Merged commit includes the following changes:
  research/object_detection/builders/box_predictor_builder_test.py
  research/object_detection/builders/graph_rewriter_builder_tf1_test.py
  research/object_detection/builders/preprocessor_builder.py
  research/object_detection/core/densepose_ops.py
  research/object_detection/core/model.py
  research/object_detection/core/preprocessor.py
  research/object_detection/core/preprocessor_test.py
  research/object_detection/core/standard_fields.py
  research/object_detection/dataset_tools/context_rcnn/add_context_to_examples.py
  research/object_detection/dataset_tools/context_rcnn/add_context_to_examples_tf1_test.py
  research/object_detection/dataset_tools/context_rcnn/create_cococameratraps_tfexample_main.py
  research/object_detection/dataset_tools/context_rcnn/create_cococameratraps_tfexample_tf1_test.py
  research/object_detection/dataset_tools/context_rcnn/generate_detection_data.py
  research/object_detection/dataset_tools/context_rcnn/generate_detection_data_tf1_test.py
  research/object_detection/dataset_tools/context_rcnn/generate_embedding_data.py
  research/object_detection/dataset_tools/context_rcnn/generate_embedding_data_tf1_test.py
  research/object_detection/dataset_tools/oid_tfrecord_creation.py
  research/object_detection/eval_util.py
  research/object_detection/meta_architectures/center_net_meta_arch.py
  research/object_detection/meta_architectures/center_net_meta_arch_tf2_test.py
  research/object_detection/meta_architectures/context_rcnn_meta_arch_tf1_test.py
  research/object_detection/metrics/oid_challenge_evaluation_utils.py
  research/object_detection/metrics/oid_vrd_challenge_evaluation_utils.py
  research/object_detection/model_main_tf2.py
  research/object_detection/packages/tf1/setup.py
  research/object_detection/packages/tf2/setup.py
  research/object_detection/protos/preprocessor.proto
  research/object_detection/utils/ops.py
  research/object_detection/utils/ops_test.py
Labels: cla: yes

#8800 Add Retinanet colab tutorial with rubber ducks data
  research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb
  research/object_detection/test_images/ducky/test/out1.jpg
  research/object_detection/test_images/ducky/test/out10.jpg
  research/object_detection/test_images/ducky/test/out11.jpg
  research/object_detection/test_images/ducky/test/out12.jpg
  research/object_detection/test_images/ducky/test/out13.jpg
  research/object_detection/test_images/ducky/test/out14.jpg
  research/object_detection/test_images/ducky/test/out15.jpg
  research/object_detection/test_images/ducky/test/out16.jpg
  research/object_detection/test_images/ducky/test/out17.jpg
  research/object_detection/test_images/ducky/test/out18.jpg
  research/object_detection/test_images/ducky/test/out19.jpg
  research/object_detection/test_images/ducky/test/out2.jpg
  research/object_detection/test_images/ducky/test/out20.jpg
  research/object_detection/test_images/ducky/test/out21.jpg
  research/object_detection/test_images/ducky/test/out22.jpg
  research/object_detection/test_images/ducky/test/out23.jpg
  research/object_detection/test_images/ducky/test/out24.jpg
  research/object_detection/test_images/ducky/test/out25.jpg
  research/object_detection/test_images/ducky/test/out26.jpg
  research/object_detection/test_images/ducky/test/out27.jpg
  research/object_detection/test_images/ducky/test/out28.jpg
  research/object_detection/test_images/ducky/test/out29.jpg
  research/object_detection/test_images/ducky/test/out3.jpg
  research/object_detection/test_images/ducky/test/out30.jpg
  research/object_detection/test_images/ducky/test/out31.jpg
  research/object_detection/test_images/ducky/test/out32.jpg
  research/object_detection/test_images/ducky/test/out33.jpg
  research/object_detection/test_images/ducky/test/out34.jpg
  research/object_detection/test_images/ducky/test/out35.jpg
  research/object_detection/test_images/ducky/test/out36.jpg
  research/object_detection/test_images/ducky/test/out37.jpg
  research/object_detection/test_images/ducky/test/out38.jpg
  research/object_detection/test_images/ducky/test/out39.jpg
  research/object_detection/test_images/ducky/test/out4.jpg
  research/object_detection/test_images/ducky/test/out40.jpg
  research/object_detection/test_images/ducky/test/out41.jpg
  research/object_detection/test_images/ducky/test/out42.jpg
  research/object_detection/test_images/ducky/test/out43.jpg
  research/object_detection/test_images/ducky/test/out44.jpg
  research/object_detection/test_images/ducky/test/out45.jpg
  research/object_detection/test_images/ducky/test/out46.jpg
  research/object_detection/test_images/ducky/test/out47.jpg
  research/object_detection/test_images/ducky/test/out48.jpg
  research/object_detection/test_images/ducky/test/out49.jpg
  research/object_detection/test_images/ducky/test/out5.jpg
  research/object_detection/test_images/ducky/test/out6.jpg
  research/object_detection/test_images/ducky/test/out7.jpg
  research/object_detection/test_images/ducky/test/out8.jpg
  research/object_detection/test_images/ducky/test/out9.jpg
  research/object_detection/test_images/ducky/train/robertducky1.jpg
  research/object_detection/test_images/ducky/train/robertducky2.jpg
  research/object_detection/test_images/ducky/train/robertducky3.jpg
  research/object_detection/test_images/ducky/train/robertducky4.jpg
  research/object_detection/test_images/ducky/train/robertducky5.jpg
Labels: cla: yes

#8807 align readme to template
  research/mobilenet/README.md
  research/mobilenet/images/latency_pixel1.png
  research/mobilenet/images/madds_top1_accuracy.png
  research/mobilenet/mobilenet_trainer.py
  research/mobilenet/mobilenet_v1.py
  research/mobilenet/mobilenet_v2.py
  research/mobilenet/mobilenet_v3.py
  research/mobilenet/requirements.txt
  research/mobilenet/scripts/load_evaluate_tf1_ckpt.sh
  research/mobilenet/tf1_loader/evaluator.py
  research/mobilenet/tf1_loader/v1_loader.py
  research/mobilenet/tf1_loader/v2_loader.py
  research/mobilenet/tf1_loader/v3_loader.py
Labels: cla: yes

#8809 Merged commit includes the following changes:
  research/object_detection/builders/model_builder.py
  research/object_detection/builders/model_builder_test.py
  research/object_detection/builders/model_builder_tf1_test.py
  research/object_detection/builders/model_builder_tf2_test.py
  research/object_detection/core/box_predictor.py
  research/object_detection/core/model.py
  research/object_detection/meta_architectures/center_net_meta_arch.py
  research/object_detection/metrics/coco_evaluation.py
  research/object_detection/metrics/coco_evaluation_test.py
  research/object_detection/model_lib.py
  research/object_detection/model_lib_v2.py
  research/object_detection/model_main.py
  research/object_detection/model_main_tf2.py
  research/object_detection/model_tpu_main.py
  research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py
  research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor_tf2_test.py
  research/object_detection/predictors/heads/head.py
  research/object_detection/protos/ssd.proto
Labels: cla: yes

#8810 Inference Colab for External
  research/object_detection/colab_tutorials/inference_tf2_colab.ipynb
Labels: cla: yes

#8818 Added *_pb2.py to object_detection gitignore.
  research/object_detection/.gitignore
Labels: cla: yes

#8819 With keypoints: Inference colab
  research/object_detection/colab_tutorials/inference_tf2_colab.ipynb
Labels: cla: yes

#8821 Interactive Ducks Colab
  research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb
  research/object_detection/utils/colab_utils.py
Labels: cla: yes

#8826 Update readme
  research/mobilenet/README.md
Labels: cla: yes

#8829 Merged commit includes the following changes:
  research/object_detection/.gitignore
  research/object_detection/CONTRIBUTING.md
  research/object_detection/builders/model_builder.py
  research/object_detection/builders/model_builder_tf2_test.py
  research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb
  research/object_detection/colab_tutorials/inference_tf2_colab.ipynb
  research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
  research/object_detection/dockerfiles/tf1/Dockerfile
  research/object_detection/dockerfiles/tf1/README.md
  research/object_detection/dockerfiles/tf2/Dockerfile
  research/object_detection/dockerfiles/tf2/README.md
  research/object_detection/model_lib_v2.py
  research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py
  research/object_detection/protos/center_net.proto
  research/object_detection/utils/colab_utils.py
  research/object_detection/utils/visualization_utils.py
  research/object_detection/utils/visualization_utils_test.py
Labels: cla: yes

#8830 Merged commit includes the following changes:
  research/object_detection/README.md
  research/object_detection/configs/tf2/center_net_hourglass104_1024x1024_coco17_tpu-32.config
  research/object_detection/configs/tf2/center_net_hourglass104_512x512_coco17_tpu-8.config
  research/object_detection/configs/tf2/center_net_resnet101_v1_fpn_512x512_coco17_tpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet101_v1_1024x1024_coco17_tpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet101_v1_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet101_v1_800x1333_coco17_gpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet152_v1_1024x1024_coco17_tpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet152_v1_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet152_v1_800x1333_coco17_gpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet50_v1_1024x1024_coco17_tpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/faster_rcnn_resnet50_v1_800x1333_coco17_gpu-8.config
  research/object_detection/configs/tf2/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8.config
  research/object_detection/configs/tf2/ssd_efficientdet_d0_512x512_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_efficientdet_d1_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_efficientdet_d2_768x768_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_efficientdet_d3_896x896_coco17_tpu-32.config
  research/object_detection/configs/tf2/ssd_efficientdet_d4_1024x1024_coco17_tpu-32.config
  research/object_detection/configs/tf2/ssd_efficientdet_d5_1280x1280_coco17_tpu-32.config
  research/object_detection/configs/tf2/ssd_efficientdet_d6_1408x1408_coco17_tpu-32.config
  research/object_detection/configs/tf2/ssd_efficientdet_d7_1536x1536_coco17_tpu-32.config
  research/object_detection/configs/tf2/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_mobilenet_v2_320x320_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_resnet101_v1_fpn_1024x1024_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_resnet101_v1_fpn_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_resnet152_v1_fpn_1024x1024_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_resnet152_v1_fpn_640x640_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8.config
  research/object_detection/configs/tf2/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.config
  research/object_detection/g3doc/challenge_evaluation.md
  research/object_detection/g3doc/configuring_jobs.md
  research/object_detection/g3doc/context_rcnn.md
  research/object_detection/g3doc/defining_your_own_model.md
  research/object_detection/g3doc/evaluation_protocols.md
  research/object_detection/g3doc/exporting_models.md
  research/object_detection/g3doc/faq.md
  research/object_detection/g3doc/installation.md
  research/object_detection/g3doc/instance_segmentation.md
  research/object_detection/g3doc/oid_inference_and_evaluation.md
  research/object_detection/g3doc/preparing_inputs.md
  research/object_detection/g3doc/release_notes.md
  research/object_detection/g3doc/running_locally.md
  research/object_detection/g3doc/running_notebook.md
  research/object_detection/g3doc/running_on_cloud.md
  research/object_detection/g3doc/running_on_mobile_tensorflowlite.md
  research/object_detection/g3doc/running_pets.md
  research/object_detection/g3doc/tf1.md
  research/object_detection/g3doc/tf1_detection_zoo.md
  research/object_detection/g3doc/tf1_training_and_evaluation.md
  research/object_detection/g3doc/tf2.md
  research/object_detection/g3doc/tf2_classification_zoo.md
  research/object_detection/g3doc/tf2_detection_zoo.md
  research/object_detection/g3doc/tf2_training_and_evaluation.md
  research/object_detection/g3doc/tpu_compatibility.md
  research/object_detection/g3doc/tpu_exporters.md
  research/object_detection/g3doc/using_your_own_dataset.md
Labels: cla: yes

#8828 Updated to include information about orbit.
  README.md
Labels: cla: yes

#8831 Inference colab with updated checkpoints
  research/object_detection/colab_tutorials/inference_tf2_colab.ipynb
Labels: cla: yes

#8833 Remove references to borg in ducks colab
  research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb
Labels: cla: yes

#8832 Merged commit includes the following changes:
  research/object_detection/README.md
Labels: cla: yes

#8834 Merged commit includes the following changes:
  research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb
  research/object_detection/colab_tutorials/inference_tf2_colab.ipynb
  research/object_detection/g3doc/tf2_detection_zoo.md
  research/object_detection/model_lib_v2.py
  research/object_detection/utils/colab_utils.py
Labels: cla: yes

#8859 Update docs to link to training and evaluation
  research/object_detection/README.md
  research/object_detection/g3doc/tf1.md
  research/object_detection/g3doc/tf2.md
Labels: cla: yes

#8866 DeepLab: Fix generation of tfrecord for Cityscapes
  research/deeplab/datasets/build_cityscapes_data.py
  research/deeplab/datasets/convert_cityscapes.sh
  research/deeplab/deprecated/segmentation_dataset.py
  research/deeplab/g3doc/cityscapes.md
Labels: cla: yes

#8867 Adds Intel's object detection models to community README
  community/README.md
Labels: cla: yes, stat:awaiting review

#8870 DeepLab: Cityscapes splits refactoring
  research/deeplab/datasets/build_cityscapes_data.py
Labels: cla: yes

#8534 deeplab/local_test.sh: Use 'bash' instead of 'sh'
  research/deeplab/g3doc/installation.md
  research/deeplab/local_test.sh
Labels: cla: yes

#8891 Add another open source colab
  research/object_detection/colab_tutorials/inference_from_saved_model_tf2_colab.ipynb
Labels: cla: yes, ready to pull

#8746 Add multilevel crop and resize functions
  research/object_detection/builders/model_builder.py
  research/object_detection/meta_architectures/context_rcnn_meta_arch.py
  research/object_detection/meta_architectures/context_rcnn_meta_arch_tf1_test.py
  research/object_detection/meta_architectures/faster_rcnn_meta_arch.py
  research/object_detection/meta_architectures/faster_rcnn_meta_arch_test_lib.py
  research/object_detection/utils/spatial_transform_ops.py
  research/object_detection/utils/spatial_transform_ops_test.py
Labels: cla: yes, ready to pull

#8909 adding option to select specific frame index
  research/object_detection/inputs.py
  research/object_detection/inputs_test.py
  research/object_detection/protos/input_reader.proto
Labels: cla: yes, ready to pull

#8843 AttentionOCR partial TF2 migration
  research/attention_ocr/README.md
  research/attention_ocr/python/data_provider.py
  research/attention_ocr/python/datasets/fsns.py
  research/attention_ocr/python/datasets/fsns_test.py
  research/attention_ocr/python/datasets/testdata/fsns/download_data.py
  research/attention_ocr/python/demo_inference.py
  research/attention_ocr/python/demo_inference_test.py
  research/attention_ocr/python/eval.py
  research/attention_ocr/python/inception_preprocessing.py
  research/attention_ocr/python/metrics.py
  research/attention_ocr/python/metrics_test.py
  research/attention_ocr/python/model.py
  research/attention_ocr/python/model_export.py
  research/attention_ocr/python/model_export_lib.py
  research/attention_ocr/python/model_export_test.py
  research/attention_ocr/python/model_test.py
  research/attention_ocr/python/sequence_layers.py
  research/attention_ocr/python/sequence_layers_test.py
  research/attention_ocr/python/train.py
  research/attention_ocr/python/utils.py
Labels: cla: yes, type:migration

#8955 Update deeplab quantized instructions
  research/deeplab/convert_to_tflite.py
  research/deeplab/g3doc/quantize.md
Labels: cla: yes

#8880 Add notebook link to readme
  research/mobilenet/README.md
Labels: cla: yes

#8979 Change NCF eval_input_dataset not to use experimental_distribute_dataset.
  official/recommendation/ncf_keras_main.py
Labels: cla: yes

#8973 Add Mobilenet v3 Edge TPU implementation
  research/mobilenet/README.md
  research/mobilenet/common_modules.py
  research/mobilenet/configs/archs.py
  research/mobilenet/mobilenet_trainer.py
  research/mobilenet/mobilenet_v1.py
  research/mobilenet/mobilenet_v2.py
  research/mobilenet/mobilenet_v3.py
  research/mobilenet/tf1_loader/evaluator.py
  research/mobilenet/tf1_loader/v1_loader.py
  research/mobilenet/tf1_loader/v2_loader.py
  research/mobilenet/tf1_loader/v3_loader.py
Labels: cla: yes, help wanted:paper implementation

#8961 Fixed typos
  official/vision/detection/dataloader/anchor.py
Labels: cla: yes, ready to pull

#8993 Fix typos in example notebook
  research/mobilenet/common_modules.py
  research/mobilenet/configs/archs.py
  research/mobilenet/notebooks/MNV1_Migrate_TF1_to_TF2_Keras.ipynb
Labels: cla: yes

#8995 add quantization example in notebook and readme
  research/mobilenet/README.md
  research/mobilenet/common_modules.py
  research/mobilenet/notebooks/MNV1_Migrate_TF1_to_TF2_Keras.ipynb
Labels: cla: yes, help wanted:paper implementation

#9009 Use distirbuted dataset for NCF evaluation.
  official/recommendation/ncf_input_pipeline.py
  official/recommendation/ncf_keras_main.py
Labels: cla: yes

#9005 layers/transformer, layers/attention
  official/nlp/modeling/layers/attention.py
  official/nlp/modeling/layers/transformer.py
  official/nlp/modeling/layers/transformer_test.py
Labels: cla: yes, ready to pull

#9020 Fixed doc strings and typos
  official/modeling/training/distributed_executor.py
  official/vision/detection/modeling/losses.py
Labels: cla: yes, ready to pull
