Repository tensorflow/models, pull requests merged in 2020-09, with the labels that each got.

#9191 Exporting code for DELG global feature
  research/delf/delf/python/training/README.md
  research/delf/delf/python/training/model/delg_model.py
  research/delf/delf/python/training/model/export_global_model.py
  research/delf/delf/python/training/model/resnet50.py
  research/delf/delf/python/training/model/resnet50_test.py
Labels: cla: yes

#9198 Exporting option for DELG local+global feature model
  research/delf/delf/python/examples/extractor.py
  research/delf/delf/python/training/README.md
  research/delf/delf/python/training/model/delf_model.py
  research/delf/delf/python/training/model/export_global_model.py
  research/delf/delf/python/training/model/export_local_and_global_model.py
  research/delf/delf/python/training/model/export_local_model.py
  research/delf/delf/python/training/model/export_model_utils.py
Labels: cla: yes

#9196 Create stale.yml
  .github/stale.yml
Labels: cla: yes

#9219 Added hyperparameter guidelines for DELF training
  research/delf/delf/python/training/README.md
Labels: cla: yes

#9246 DELG: adding models pre-trained on GLDv2-clean
  research/delf/README.md
  research/delf/delf/python/delg/DELG_INSTRUCTIONS.md
  research/delf/delf/python/delg/r101delg_gldv2clean_config.pbtxt
  research/delf/delf/python/delg/r50delg_gldv2clean_config.pbtxt
Labels: cla: yes

#8962 Identity box coder, similarity calculator, target assigner
  research/object_detection/core/region_similarity_calculator.py
  research/object_detection/core/region_similarity_calculator_test.py
  research/object_detection/core/target_assigner.py
  research/object_detection/core/target_assigner_test.py
Labels: cla: yes, ready to pull

#9252 DELG: fix small typo on extractor.py
  research/delf/delf/python/examples/extractor.py
Labels: cla: yes

#9207 fix `base_url`
  research/slim/datasets/imagenet.py
Labels: cla: yes

#6095 Define a variable named base_name in Prerequisites step
  research/slim/nets/mobilenet/mobilenet_example.ipynb
Labels: cla: yes, stat:awaiting review

#8421 fix index error, to support non-square kernels
  research/slim/nets/mobilenet_v1.py
Labels: cla: yes, stat:awaiting review

#9253 Adds Intel-optimized NLP and Recommender models to community README
  community/README.md
Labels: cla: yes, stat:awaiting review

#9305 remove redundant code
  research/mobilenet/common_modules.py
Labels: cla: yes

#9268 Create bot-config.yml
  .github/bot-config.yml
Labels: cla: yes

#9324 Rename bot-config.yml to bot_config.yml
  .github/bot_config.yml
Labels: cla: yes

#9222 replace tf.compat.v1.logging with absl.logging for deep_speech
  research/deep_speech/data/dataset.py
  research/deep_speech/data/download.py
  research/deep_speech/deep_speech.py
Labels: cla: yes, stat:awaiting testing
