Repository tensorflow/models, pull requests merged in 2020-08, with the labels that each got.

#9021 Bugfix in context r-cnn scripts
  research/object_detection/dataset_tools/context_rcnn/add_context_to_examples.py
Labels: cla: yes, ready to pull

#9024 Fix Mobilenetv3 edgetpu bugs
  research/mobilenet/configs/archs.py
  research/mobilenet/mobilenet_trainer.py
  research/mobilenet/mobilenet_v1.py
  research/mobilenet/mobilenet_v2.py
  research/mobilenet/mobilenet_v3.py
Labels: cla: yes, help wanted:paper implementation

#9022 OnDeviceEmbedding and test case
  official/nlp/modeling/layers/on_device_embedding.py
  official/nlp/modeling/layers/on_device_embedding_test.py
Labels: cla: yes, ready to pull

#8894 moving fpn message to fpn.proto
  research/object_detection/protos/faster_rcnn.proto
  research/object_detection/protos/fpn.proto
  research/object_detection/protos/ssd.proto
Labels: cla: yes, ready to pull

#9007 Fix notebook URL
  research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
Labels: cla: yes, ready to pull

#8943 Hungarian Matcher
  research/object_detection/matchers/hungarian_matcher.py
  research/object_detection/matchers/hungarian_matcher_tf2_test.py
Labels: cla: yes, ready to pull

#8893 Move to keraslayers fasterrcnn fpn keras feature extractor
  research/object_detection/models/faster_rcnn_resnet_v1_fpn_keras_feature_extractor.py
  research/object_detection/models/faster_rcnn_resnet_v1_fpn_keras_feature_extractor_tf2_test.py
  research/object_detection/utils/ops.py
Labels: cla: yes, ready to pull

#9043 Losses and ops with giou -- new pr
  research/object_detection/core/box_list_ops.py
  research/object_detection/core/box_list_ops_test.py
  research/object_detection/core/losses.py
  research/object_detection/core/losses_test.py
  research/object_detection/utils/ops.py
  research/object_detection/utils/ops_test.py
Labels: cla: yes, ready to pull

#8895 Adjust frcnn meta arch to multilevel rpn feature
  research/object_detection/builders/model_builder.py
  research/object_detection/meta_architectures/context_rcnn_meta_arch.py
  research/object_detection/meta_architectures/context_rcnn_meta_arch_test.py
  research/object_detection/meta_architectures/faster_rcnn_meta_arch.py
  research/object_detection/meta_architectures/faster_rcnn_meta_arch_test.py
  research/object_detection/meta_architectures/faster_rcnn_meta_arch_test_lib.py
  research/object_detection/meta_architectures/rfcn_meta_arch.py
Labels: cla: yes, ready to pull

#9071 attention_initializer arguement
  official/nlp/modeling/layers/transformer.py
  official/nlp/modeling/layers/transformer_test.py
Labels: cla: yes, ready to pull

#9069 Update bert README
  official/nlp/bert/README.md
Labels: cla: yes, ready to pull

#8984 frozen inference graphs tf 1 documentation update
  research/object_detection/g3doc/tf1_detection_zoo.md
Labels: cla: yes, ready to pull

#9077 Made VGGish and YAMNet work in TF2 without disabling TF2 behavior.
  research/audioset/vggish/README.md
  research/audioset/vggish/vggish_inference_demo.py
  research/audioset/vggish/vggish_slim.py
  research/audioset/vggish/vggish_smoke_test.py
  research/audioset/vggish/vggish_train_demo.py
  research/audioset/yamnet/README.md
Labels: cla: yes

#9080 VGGish embeddings are pre-activation, not post-activation.
  research/audioset/vggish/README.md
  research/audioset/vggish/vggish_slim.py
  research/audioset/vggish/vggish_smoke_test.py
  research/audioset/vggish/vggish_train_demo.py
Labels: cla: yes

#9085 Remove benchmark folder from the master branch. They are stale.
  official/benchmark/__init__.py
  official/benchmark/benchmark_wrappers.py
  official/benchmark/bert_benchmark.py
  official/benchmark/bert_benchmark_utils.py
  official/benchmark/bert_pretrain_benchmark.py
  official/benchmark/bert_squad_benchmark.py
  official/benchmark/datastore/schema/benchmark_metric.json
  official/benchmark/datastore/schema/benchmark_run.json
  official/benchmark/datastore/schema/benchmark_run_status.json
  official/benchmark/keras_benchmark.py
  official/benchmark/keras_cifar_benchmark.py
  official/benchmark/keras_imagenet_benchmark.py
  official/benchmark/models/__init__.py
  official/benchmark/models/cifar_preprocessing.py
  official/benchmark/models/resnet_cifar_main.py
  official/benchmark/models/resnet_cifar_model.py
  official/benchmark/models/resnet_cifar_test.py
  official/benchmark/models/resnet_imagenet_main.py
  official/benchmark/models/resnet_imagenet_test.py
  official/benchmark/models/resnet_imagenet_test_tpu.py
  official/benchmark/models/shakespeare/README.md
  official/benchmark/models/shakespeare/__init__.py
  official/benchmark/models/shakespeare/shakespeare_main.py
  official/benchmark/models/synthetic_util.py
  official/benchmark/ncf_keras_benchmark.py
  official/benchmark/nhnet_benchmark.py
  official/benchmark/owner_utils.py
  official/benchmark/owner_utils_test.py
  official/benchmark/perfzero_benchmark.py
  official/benchmark/resnet_ctl_imagenet_benchmark.py
  official/benchmark/retinanet_benchmark.py
  official/benchmark/shakespeare_benchmark.py
  official/benchmark/tfhub_memory_usage_benchmark.py
  official/benchmark/transformer_benchmark.py
  official/benchmark/unet3d_benchmark.py
  official/benchmark/xlnet_benchmark.py
Labels: cla: yes

#9081 Added a TF-Hub-compatible SavedModel exporter for VGGish.
  research/audioset/vggish/vggish_export_tfhub.py
  research/audioset/vggish/vggish_inference_demo.py
  research/audioset/vggish/vggish_smoke_test.py
  research/audioset/vggish/vggish_train_demo.py
Labels: cla: yes

#9055 add config file for faster rcnn resnet 50 fpn on dataset coco17 using tpu-8
  research/object_detection/configs/tf2/faster_rcnn_resnet50_v1_fpn_640x640_coco17_tpu-8.config
Labels: cla: yes, ready to pull

#9092 Input/Output tweaks for YAMNet and VGGish.
  research/audioset/yamnet/features.py
  research/audioset/yamnet/inference.py
  research/audioset/yamnet/params.py
  research/audioset/yamnet/yamnet.py
  research/audioset/yamnet/yamnet_visualization.ipynb
Labels: cla: yes

#9097 context R-CNN bugfix and documentation fix
  research/object_detection/meta_architectures/context_rcnn_lib_tf2.py
Labels: cla: yes, ready to pull

#9086 exporter final version
  research/object_detection/exporter_lib_tf2_test.py
  research/object_detection/exporter_lib_v2.py
  research/object_detection/exporter_main_v2.py
Labels: cla: yes, ready to pull

#9091 a small typo in the read me file
  official/nlp/bert/bert_cloud_tpu.md
Labels: cla: yes, ready to pull

#9090 Seq2SeqTransformer Model
  official/nlp/modeling/models/seq2seq_transformer.py
  official/nlp/modeling/models/seq2seq_transformer_test.py
Labels: cla: yes, ready to pull

#9095 DELF updates
  research/delf/delf/python/delg/extract_features.py
  research/delf/delf/python/delg/measure_latency.py
  research/delf/delf/python/delg/perform_retrieval.py
  research/delf/delf/python/detect_to_retrieve/cluster_delf_features.py
  research/delf/delf/python/detect_to_retrieve/extract_query_features.py
  research/delf/delf/python/detect_to_retrieve/image_reranking.py
  research/delf/delf/python/detect_to_retrieve/perform_retrieval.py
  research/delf/delf/python/examples/match_images.py
  research/delf/delf/python/training/model/__init__.py
  research/delf/delf/python/training/model/delf_model.py
  research/delf/delf/python/training/model/delg_model.py
  research/delf/delf/python/training/model/resnet50.py
  research/delf/delf/python/training/model/resnet50_test.py
  research/delf/delf/python/training/train.py
Labels: cla: yes

#8696 1. update to tf2.x for deep_speech
  research/deep_speech/data/dataset.py
  research/deep_speech/data/download.py
  research/deep_speech/deep_speech.py
  research/deep_speech/deep_speech_model.py
Labels: cla: yes, stat:awaiting testing

#9108 Move DELF resizing code into utils.py, which is more appropriate than extractor.py.
  research/delf/delf/python/examples/extractor.py
  research/delf/delf/python/utils.py
  research/delf/delf/python/utils_test.py
Labels: cla: yes

#9103 Forward test for refactoring
  official/nlp/transformer/transformer_forward_test.py
Labels: cla: yes, ready to pull

#9070 Consider regression model in predict mode
  official/nlp/bert/run_classifier.py
Labels: cla: yes, models:official, ready to pull

#9120 Context R-CNN TF 2: move batch norm between dense and activation
  research/object_detection/meta_architectures/context_rcnn_lib_tf2.py
Labels: cla: yes, ready to pull

#9098 Added TF-Lite-compatible feature extractor and model exporter for YAMNet
  research/audioset/vggish/vggish_export_tfhub.py
  research/audioset/yamnet/export.py
  research/audioset/yamnet/features.py
  research/audioset/yamnet/inference.py
  research/audioset/yamnet/params.py
  research/audioset/yamnet/yamnet.py
  research/audioset/yamnet/yamnet_test.py
Labels: cla: yes, models:research

#9112 README update for DELG training
  research/delf/delf/python/training/README.md
Labels: cla: yes

#9145 Refactor DELG extraction + Release latest DELG paper models
  research/delf/README.md
  research/delf/delf/python/delg/DELG_INSTRUCTIONS.md
  research/delf/delf/python/delg/r101delg_gld_config.pbtxt
  research/delf/delf/python/delg/r50delg_gld_config.pbtxt
  research/delf/delf/python/examples/extractor.py
  research/delf/delf/python/google_landmarks_dataset/README.md
  research/delf/delf/python/google_landmarks_dataset/rn101_af_gldv2clean_config.pbtxt
Labels: cla: yes

#8768 End-to-end Data processing for AVA TF records
  research/object_detection/dataset_tools/create_ava_actions_tf_record.py
  research/object_detection/dataset_tools/download_and_preprocess_ava.sh
  research/object_detection/dataset_tools/seq_example_util.py
  research/object_detection/dataset_tools/seq_example_util_test.py
Labels: cla: yes, ready to pull

#9163 fix ValueError for adversarial_text
  research/adversarial_text/README.md
Labels: cla: yes
