Repository tensorflow/models, pull requests merged in 2020-02, with the labels that each got.

#8121 Remove differential_privacy and morph_net from research folder
  CODEOWNERS
  research/README.md
  research/differential_privacy/README.md
  research/morph_net/README.md
  research/morph_net/__init__.py
  research/morph_net/framework/README.md
  research/morph_net/framework/__init__.py
  research/morph_net/framework/concat_and_slice_regularizers.py
  research/morph_net/framework/concat_and_slice_regularizers_test.py
  research/morph_net/framework/generic_regularizers.py
  research/morph_net/framework/grouping_regularizers.py
  research/morph_net/framework/grouping_regularizers_test.py
  research/morph_net/framework/op_regularizer_manager.py
  research/morph_net/framework/op_regularizer_manager_test.py
  research/morph_net/g3doc/grouping.png
  research/morph_net/g3doc/histogram.png
  research/morph_net/g3doc/tensorboard.png
  research/morph_net/network_regularizers/__init__.py
  research/morph_net/network_regularizers/bilinear_cost_utils.py
  research/morph_net/network_regularizers/bilinear_cost_utils_test.py
  research/morph_net/network_regularizers/flop_regularizer.py
  research/morph_net/network_regularizers/flop_regularizer_test.py
  research/morph_net/network_regularizers/model_size_regularizer.py
  research/morph_net/op_regularizers/__init__.py
  research/morph_net/op_regularizers/conv_group_lasso_regularizer.py
  research/morph_net/op_regularizers/conv_group_lasso_regularizer_test.py
  research/morph_net/op_regularizers/gamma_l1_regularizer.py
  research/morph_net/op_regularizers/gamma_mapper.py
  research/morph_net/op_regularizers/gamma_mapper_test.py
  research/morph_net/testing/__init__.py
  research/morph_net/testing/op_regularizer_stub.py
Labels: cla: yes

#8140 Update README.md
  research/tcn/README.md
Labels: cla: no

#8147 remove tensorrt as the example repo has been moved for a while
  research/tensorrt/README.md
Labels: cla: yes

#8152 fix "Unknown command line flag 'export_dir'"
  research/deep_speech/deep_speech.py
Labels: cla: yes

#8158 ISSUES.md
  ISSUES.md
Labels: cla: yes

#8161 Update yamnet_visualization.ipynb to work under TF2.0.
  research/audioset/yamnet/yamnet_visualization.ipynb
Labels: cla: yes

#8159 Creating issue templates for models
  .github/ISSUE_TEMPLATE/00-official-bug-report-issue.md
  .github/ISSUE_TEMPLATE/10-official-documentation-issue.md
  .github/ISSUE_TEMPLATE/20-official-feature-request-issue.md
  .github/ISSUE_TEMPLATE/30-research-bug-report-issue.md
  .github/ISSUE_TEMPLATE/40-research-documentation-issue.md
  .github/ISSUE_TEMPLATE/50-research-feature-request-issue.md
  ISSUES.md
  github/ISSUE_TEMPLATE/00-official-bug-issue.md
  github/ISSUE_TEMPLATE/10-official-documentation-issue.md
  github/ISSUE_TEMPLATE/20-official-feature-request-issue.md
  github/ISSUE_TEMPLATE/30-research-bug-issue.md
Labels: cla: yes

#8168 Update 40-research-documentation-issue.md
  .github/ISSUE_TEMPLATE/40-research-documentation-issue.md
Labels: cla: yes

#8167 Update 10-official-documentation-issue.md
  .github/ISSUE_TEMPLATE/10-official-documentation-issue.md
  .github/ISSUE_TEMPLATE/40-research-documentation-issue.md
Labels: cla: yes

#8169 Fix the transformer link
  official/README-TPU.md
Labels: cla: yes, ready to pull

#8174 YAMNet variable sr
  research/audioset/yamnet/yamnet_visualization.ipynb
Labels: cla: yes

#8180 Update README.md with a note for common TF 2.x compatibility issue.
  research/README.md
Labels: cla: yes

#8191 Readme Updated for Python3
  official/README.md
Labels: cla: yes, ready to pull

#8203 Add the tf2-compatible graph wrapping idiom to inference.py.
  research/audioset/yamnet/inference.py
Labels: cla: yes

#8218 Updated stackoverflow tag
  .github/ISSUE_TEMPLATE/50-research-feature-request-issue.md
Labels: cla: yes

#8217 Updated stackoverflow tag
  .github/ISSUE_TEMPLATE/40-research-documentation-issue.md
Labels: cla: yes

#8216 Updated stackoverflow tag
  .github/ISSUE_TEMPLATE/30-research-bug-report-issue.md
Labels: cla: yes

#8215 Updated stackoverflow tag
  .github/ISSUE_TEMPLATE/20-official-feature-request-issue.md
Labels: cla: yes

#8214 Update 10-official-documentation-issue.md
  .github/ISSUE_TEMPLATE/10-official-documentation-issue.md
Labels: cla: yes

#8213 Updated stackoverflow tag
  .github/ISSUE_TEMPLATE/00-official-bug-report-issue.md
Labels: cla: yes

#8219 Create 60-questions-help-issue.md
  .github/ISSUE_TEMPLATE/60-questions-help-issue.md
Labels: cla: yes

#8220 Create config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla: yes
