Repository tensorflow/models, pull requests merged in 2020-05, with the labels that each got.

#8443 Add a new "Community" directory
  README.md
  community/README.md
Labels: cla: yes, stat:awaiting review, stat:on hold

#8466 Allow deeplab dataset script to be run from any location
  research/deeplab/datasets/download_and_convert_voc2012.sh
Labels: cla: yes

#8467 Add new templates and update README files
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/README_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  community/README.md
  official/README.md
  research/README.md
Labels: cla: yes, stat:awaiting review

#8472 DELF: update TF required version in setup.py; fix skimage issue with latest version
  research/delf/delf/python/detect_to_retrieve/image_reranking.py
  research/delf/setup.py
Labels: cla: yes

#8478 Delete files no longer used
  .gitmodules
  WORKSPACE
Labels: cla: yes, stat:awaiting review

#8483 Small update to DELF training README.
  research/delf/delf/python/training/README.md
Labels: cla: yes

#8492 Revise issue templates
  .github/ISSUE_TEMPLATE/00-official-bug-report-issue.md
  .github/ISSUE_TEMPLATE/10-official-documentation-issue.md
  .github/ISSUE_TEMPLATE/20-official-feature-request-issue.md
  .github/ISSUE_TEMPLATE/30-research-bug-report-issue.md
  .github/ISSUE_TEMPLATE/40-research-documentation-issue.md
  .github/ISSUE_TEMPLATE/50-research-feature-request-issue.md
Labels: cla: yes, stat:awaiting review

#8489 Updating cifar download links
  research/autoaugment/README.md
Labels: cla: yes, stat:awaiting review

#8510 Add description about the option 'num_gpus' for NCF model
  official/recommendation/README.md
Labels: cla: yes, ready to pull

#8508 Add bert's instruction about using a checkpoint on local storage
  official/nlp/bert/README.md
Labels: cla: yes, ready to pull

#8517 Update deeplab/local_test.sh
  research/deeplab/local_test.sh
Labels: cla: yes

#8528 Fix typo in vision/detection README.md
  official/vision/detection/README.md
Labels: cla: yes, ready to pull

#8419 Use round() instead of int() when displaying score
  research/object_detection/utils/visualization_utils.py
Labels: cla: yes, stat:awaiting review

#8544 Python Version
  research/learned_optimizer/README.md
Labels: cla: yes

#8553 Add DELG code
  research/delf/README.md
  research/delf/delf/protos/delf_config.proto
  research/delf/delf/python/delg/DELG_INSTRUCTIONS.md
  research/delf/delf/python/delg/delg_gld_config.pbtxt
  research/delf/delf/python/delg/extract_features.py
  research/delf/delf/python/delg/perform_retrieval.py
  research/delf/delf/python/detect_to_retrieve/boxes_and_features_extraction.py
  research/delf/delf/python/detect_to_retrieve/extract_query_features.py
  research/delf/delf/python/detect_to_retrieve/image_reranking.py
  research/delf/delf/python/examples/extract_features.py
  research/delf/delf/python/examples/extractor.py
  research/delf/delf/python/examples/extractor_test.py
Labels: cla: yes

#8555 Fix link in README.md
  official/README.md
Labels: cla: yes, ready to pull

#8557 Add GLDv2 baseline in DELF codebase
  research/delf/README.md
  research/delf/delf/python/delg/extract_features.py
  research/delf/delf/python/google_landmarks_dataset/README.md
  research/delf/delf/python/google_landmarks_dataset/rn101_af_gldv2clean_config.pbtxt
Labels: cla: yes

#8558 Small documentation update
  research/delf/delf/python/delg/DELG_INSTRUCTIONS.md
  research/delf/delf/python/google_landmarks_dataset/README.md
  research/delf/delf/python/training/README.md
Labels: cla: yes

#8542 bugfix: unused and incorrect variable name
  official/nlp/transformer/data_download.py
Labels: cla: yes, ready to pull

#8591 Moved code from TF1 to TF2 for DELF logging, testing directories and feature extraction scripts
  research/delf/delf/__init__.py
  research/delf/delf/python/delf_v1.py
  research/delf/delf/python/delg/extract_features.py
  research/delf/delf/python/detect_to_retrieve/boxes_and_features_extraction.py
  research/delf/delf/python/detect_to_retrieve/dataset_test.py
  research/delf/delf/python/detect_to_retrieve/extract_query_features.py
  research/delf/delf/python/examples/extract_boxes.py
  research/delf/delf/python/examples/extract_features.py
  research/delf/delf/python/examples/match_images.py
  research/delf/delf/python/google_landmarks_dataset/dataset_file_io_test.py
  research/delf/delf/python/utils.py
Labels: cla: yes
