Repository tensorflow/models, pull requests merged in 2020-04, with the labels that each got.

#8350 remove research/astronet/
  CODEOWNERS
  research/README.md
  research/astronet/README.md
Labels: cla: yes

#8353 Fixed typo in readme
  README.md
Labels: cla: yes

#8352 add edgetpu deeplab
  research/deeplab/README.md
  research/deeplab/core/feature_extractor.py
  research/deeplab/g3doc/model_zoo.md
Labels: cla: yes

#8355 Move a number of FLAGS from lower-level functions to the top-level
  official/nlp/data/create_pretraining_data.py
Labels: cla: yes, ready to pull

#8358 Update README.md
  research/rebar/README.md
Labels: cla: yes

#8360 Updated README and CODEOWNERS
  CODEOWNERS
  research/README.md
Labels: cla: yes

#8364 no flag named video
  research/vid2depth/README.md
Labels: cla: yes

#8372 Add num_summed_dimensions to get_config() of the DenseEinsum layer
  official/nlp/modeling/layers/dense_einsum.py
Labels: cla: yes, ready to pull

#8390 Updated README files of research models
  research/adv_imagenet_models/README.md
  research/adversarial_crypto/README.md
  research/adversarial_logit_pairing/README.md
  research/adversarial_text/README.md
  research/audioset/README.md
  research/autoencoder/README.md
  research/cognitive_mapping_and_planning/README.md
  research/deep_speech/README.md
  research/delf/README.md
  research/domain_adaptation/README.md
  research/efficient-hrl/README.md
  research/fivo/README.md
  research/global_objectives/README.md
  research/im2txt/README.md
  research/inception/README.md
  research/learned_optimizer/README.md
  research/learning_to_remember_rare_events/README.md
  research/lexnet_nc/README.md
  research/lm_1b/README.md
  research/lm_commonsense/README.md
  research/marco/README.md
  research/maskgan/README.md
  research/namignizer/README.md
  research/neural_gpu/README.md
  research/neural_programmer/README.md
  research/next_frame_prediction/README.md
  research/object_detection/README.md
  research/pcl_rl/README.md
  research/qa_kg/README.md
  research/real_nvp/README.md
  research/sentiment_analysis/README.md
  research/seq2species/README.md
  research/skip_thoughts/README.md
  research/steve/README.md
  research/struct2depth/README.md
  research/swivel/README.md
  research/textsum/README.md
  research/transformer/README.md
  research/vid2depth/README.md
  research/video_prediction/README.md
Labels: cla: yes

#8385 fix official.vision.detection.ops import error
  official/vision/detection/ops/__init__.py
Labels: cla: yes, ready to pull

#8382 Corrected tensorflow library install instruction
  research/delf/INSTALL_INSTRUCTIONS.md
Labels: cla: yes

#8269 Remove stray period in yamnet README.md.
  research/audioset/yamnet/README.md
Labels: cla: yes

#8406 fix no attribute 'per_replica_batch_size'
  research/deep_speech/deep_speech.py
Labels: cla: yes

#8351 Fix paths/permissions in download_and_preprocess_flowers.sh to work e…
  research/inception/inception/data/build_image_data.py
  research/inception/inception/data/download_and_preprocess_flowers.sh
Labels: cla: yes

#7181 Update 4_Neural_Style_Transfer_with_Eager_Execution.ipynb
  research/nst_blogpost/4_Neural_Style_Transfer_with_Eager_Execution.ipynb
Labels: cla: yes

#7871 Update README.md
  research/rebar/README.md
Labels: cla: yes

#5571 Fixes Python 3.x error and dependency deprecation warning in research/skip_thoughts
  research/skip_thoughts/skip_thoughts/encoder_manager.py
  research/skip_thoughts/skip_thoughts/vocabulary_expansion.py
Labels: cla: yes

#6854 Fixed typo in prediction_train.py
  research/video_prediction/prediction_train.py
Labels: cla: yes

#8223 Guard the unsafe tf.log to prevent NAN
  research/video_prediction/prediction_train.py
Labels: cla: yes

#5399 Add utilities and documentation for preparing training data.
  research/lexnet_nc/README.md
  research/lexnet_nc/extract_paths.py
  research/lexnet_nc/learn_path_embeddings.py
  research/lexnet_nc/lexnet_common.py
  research/lexnet_nc/path_model.py
  research/lexnet_nc/sorted_paths_to_examples.py
  research/lexnet_nc/text_embeddings_to_binary.py
Labels: cla: yes

#8221 Guard the unsafe tf.exp to prevent Inf cost
  research/lfads/lfads.py
  research/lfads/run_lfads.py
Labels: cla: yes

#4954 Fix FSNS dataset set path construction on Windows.
  research/attention_ocr/python/datasets/fsns.py
Labels: cla: yes

#7342 struct2depth model.py does not apply imagenet normalization during inference
  research/struct2depth/model.py
Labels: cla: yes

#8153 Small typo fixes to the tutorial.
  research/object_detection/object_detection_tutorial.ipynb
Labels: cla: yes

#7984 Update README.md
  research/object_detection/dockerfiles/android/README.md
Labels: cla: yes, models:research

#5074 Fix typo
  research/object_detection/g3doc/preparing_inputs.md
Labels: cla: yes

#4901 Typo on string #237
  research/street/README.md
Labels: cla: yes

#8354 Fix maintainers list into a table for easy read.
  research/object_detection/README.md
Labels: cla: yes

#5407 Fix Instructions for installing swiftshader.
  research/cognitive_mapping_and_planning/README.md
Labels: cla: yes

#5049 Update VariationalAutoencoder.py
  research/autoencoder/autoencoder_models/VariationalAutoencoder.py
Labels: cla: yes

#8103 update link of tflite conversion command lines in research/object_detection/g3doc/running_on_mobile_tensorflowlite.md
  research/object_detection/g3doc/running_on_mobile_tensorflowlite.md
Labels: cla: yes

#4977 Update directory path and update bashrc file
  research/object_detection/g3doc/installation.md
Labels: cla: yes

#5164 Update the URL of one script
  research/slim/README.md
Labels: cla: yes

#6415 Update installation.md
  research/object_detection/g3doc/installation.md
Labels: cla: yes

#7581 Updating documentation for pycocotools
  research/object_detection/g3doc/installation.md
Labels: cla: yes

#7951 Added .values to series object
  research/deep_contextual_bandits/bandits/data/data_sampler.py
Labels: cla: yes

#7338 Replace deprecated functions tf.rnn.nn 2 tf.contrib.rnn
  research/deep_speech/deep_speech_model.py
Labels: cla: yes

#6097 Remove Python compiled files from deep_contextual_bandits
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/bb_alpha_divergence_model.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/bf_variational_neural_bandit_model.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/bootstrapped_bnn_sampling.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/fixed_policy_sampling.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/linear_full_posterior_sampling.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/multitask_gp.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/neural_bandit_model.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/neural_linear_sampling.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/parameter_noise_sampling.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/posterior_bnn_sampling.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/uniform_sampling.cpython-36.pyc
  research/deep_contextual_bandits/bandits/algorithms/__pycache__/variational_neural_bandit_model.cpython-36.pyc
  research/deep_contextual_bandits/bandits/core/__pycache__/bandit_algorithm.cpython-36.pyc
  research/deep_contextual_bandits/bandits/core/__pycache__/bayesian_nn.cpython-36.pyc
  research/deep_contextual_bandits/bandits/core/__pycache__/contextual_bandit.cpython-36.pyc
  research/deep_contextual_bandits/bandits/core/__pycache__/contextual_dataset.cpython-36.pyc
  research/deep_contextual_bandits/bandits/data/__pycache__/data_sampler.cpython-36.pyc
  research/deep_contextual_bandits/bandits/data/__pycache__/synthetic_data_sampler.cpython-36.pyc
Labels: cla: yes

#7292 Update dataset websites in detection_model_zoo.md
  research/object_detection/g3doc/detection_model_zoo.md
Labels: cla: yes

#7152 Update 4_Neural_Style_Transfer_with_Eager_Execution.ipynb
  research/nst_blogpost/4_Neural_Style_Transfer_with_Eager_Execution.ipynb
Labels: cla: yes

#6623 Fix filename
  research/object_detection/g3doc/running_on_mobile_tensorflowlite.md
Labels: cla: yes

#8089 Fix typo in object detection export_graph example usage
  research/object_detection/export_inference_graph.py
  research/object_detection/export_tflite_ssd_graph.py
Labels: cla: yes

#7897 Fix android object_detection Dockerfile
  research/object_detection/dockerfiles/android/Dockerfile
Labels: cla: yes

#8057 Updates SSD model links to fixed versions
  research/object_detection/g3doc/detection_model_zoo.md
Labels: cla: yes

#5771 Fixed broken link
  research/object_detection/g3doc/oid_inference_and_evaluation.md
Labels: cla: yes

#8436 tf.compat.v1.name_scope to tf.name_scope
  official/vision/image_classification/resnet/common.py
Labels: cla: yes, ready to pull, stat:awaiting review

#8439 Handle non-login shell case in stdout utility
  official/utils/flags/_conventions.py
Labels: cla: yes, ready to pull, stat:awaiting review

#8403 Make BertPretrainer to accept embedding_table explicitly
  official/nlp/bert/bert_models.py
  official/nlp/modeling/models/bert_pretrainer.py
  official/nlp/modeling/networks/masked_lm.py
Labels: cla: yes, models:official, ready to pull, stat:awaiting review

#8447 Added skimage troubleshooting
  research/delf/EXTRACTION_MATCHING.md
Labels: cla: yes
