Repository tensorflow/models, pull requests merged in 2020-06, with the labels that each got.

#8606 Add relative positional embedding to KerasBERT
  official/nlp/modeling/layers/masked_softmax.py
  official/nlp/modeling/layers/position_embedding.py
  official/nlp/modeling/layers/position_embedding_test.py
  official/nlp/transformer/transformer.py
Labels: cla: yes

#8617 Add relative positional embedding to KerasBERT
  official/nlp/modeling/layers/position_embedding.py
  official/nlp/modeling/layers/position_embedding_test.py
  official/nlp/transformer/transformer.py
Labels: cla: yes, ready to pull

#8619 Revert "Add relative positional embedding to KerasBERT (#8617)"
  official/nlp/modeling/layers/position_embedding.py
  official/nlp/modeling/layers/position_embedding_test.py
  official/nlp/transformer/transformer.py
Labels: cla: yes

#8620 Revert "Revert "Add relative positional embedding to KerasBERT (#8617)""
  official/nlp/modeling/layers/position_embedding.py
  official/nlp/modeling/layers/position_embedding_test.py
  official/nlp/transformer/transformer.py
Labels: cla: yes, ready to pull

#8616 Scripts to download GLDv2 data for DELF training and to install DELF package
  research/delf/delf/python/training/download_dataset.sh
  research/delf/delf/python/training/install_delf.sh
Labels: cla: yes

#8625 Adds CPU-optimized models to community README
  community/README.md
Labels: cla: yes

#8629 Foundation of MobilenetV1, V2, V3 in TF2
  research/mobilenet/__init__.py
  research/mobilenet/common_modules.py
  research/mobilenet/configs/__init__.py
  research/mobilenet/configs/archs.py
  research/mobilenet/configs/dataset.py
  research/mobilenet/configs/defaults.py
  research/mobilenet/dataset_loader.py
  research/mobilenet/mobilenet_trainer.py
  research/mobilenet/mobilenet_v1_model.py
  research/mobilenet/mobilenet_v2_model.py
  research/mobilenet/mobilenet_v3_model.py
  research/mobilenet/requirements.txt
  research/mobilenet/tests/__init__.py
  research/mobilenet/tests/mobilenet_v1_model_test.py
  research/mobilenet/tests/mobilenet_v2_model_test.py
  research/mobilenet/tests/mobilenet_v3_model_test.py
Labels: cla: yes, help wanted:paper implementation

#8565 Repeated tf.cast in official/image_classification
  official/vision/image_classification/dataset_factory.py
Labels: cla: yes, ready to pull

#8650 Push to Github of changes to the TFRecord generation of GLDv2 dataset
  research/delf/delf/python/training/build_image_dataset.py
Labels: cla: yes

#8654 Update documentation
  research/slim/nets/mobilenet_v1.md
Labels: cla: yes

#8661 Make quantizable_separable_conv2d initializer explicitly configurable…
  research/lstm_object_detection/lstm/lstm_cells.py
  research/lstm_object_detection/lstm/utils.py
  research/lstm_object_detection/meta_architectures/lstm_ssd_meta_arch_test.py
Labels: cla: yes

#8662 update a3c_cartpole.py to tf2.x
  research/a3c_blogpost/README.md
  research/a3c_blogpost/a3c_cartpole.py
Labels: cla: yes

#8663 DELF Training Documentation Update
  research/delf/delf/python/training/README.md
Labels: cla: yes

#8633 install tf_slim
  research/object_detection/object_detection_tutorial.ipynb
Labels: cla: yes

#8670 Push to Github of changes to DELF package
  research/delf/delf/python/delg/extract_features.py
  research/delf/delf/python/delg/measure_latency.py
  research/delf/delf/python/detect_to_retrieve/boxes_and_features_extraction.py
  research/delf/delf/python/detect_to_retrieve/extract_query_features.py
  research/delf/delf/python/examples/detector.py
  research/delf/delf/python/examples/extract_boxes.py
  research/delf/delf/python/examples/extract_features.py
  research/delf/delf/python/examples/extractor.py
  research/delf/delf/python/feature_extractor.py
  research/delf/delf/python/training/build_image_dataset.py
Labels: cla: yes

#8678 Push to Github of TF2 changes to DELF package
  research/delf/delf/python/box_io_test.py
  research/delf/delf/python/datum_io_test.py
  research/delf/delf/python/delf_v1.py
  research/delf/delf/python/detect_to_retrieve/aggregation_extraction.py
  research/delf/delf/python/feature_aggregation_extractor.py
  research/delf/delf/python/feature_aggregation_extractor_test.py
  research/delf/delf/python/feature_extractor.py
  research/delf/delf/python/feature_extractor_test.py
  research/delf/delf/python/feature_io_test.py
  research/delf/delf/python/training/datasets/googlelandmarks.py
  research/delf/delf/python/training/train.py
Labels: cla: yes

#8679 Fix to DELF package
  research/delf/delf/__init__.py
Labels: cla: yes

#8677 Update WikiTableQuestions info
  research/neural_programmer/README.md
Labels: cla: yes

#8687 fix "No module named 'official.utils.logs'" for deep_speech
  research/deep_speech/deep_speech.py
Labels: cla: yes

#8694 Remove logger dependency from deep speech
  research/deep_speech/deep_speech.py
Labels: cla: yes

#8697 Release Context RCNN code and pre-trained model.
  research/object_detection/README.md
  research/object_detection/g3doc/context_rcnn.md
  research/object_detection/model_lib.py
  research/object_detection/samples/configs/context_rcnn_resnet101_snapshot_serengeti_sync.config
Labels: cla: yes

#7715 #7532 Adding model save support for Sentiment Analysis model
  research/sentiment_analysis/sentiment_main.py
Labels: cla: yes, stat:awaiting review

#8722 Fix TypeError when calculating normalized_error
  research/efficient-hrl/agent.py
Labels: cla: yes

#8728 Merged commit includes the following changes:
  research/object_detection/builders/hyperparams_builder.py
  research/object_detection/builders/hyperparams_builder_test.py
  research/object_detection/builders/preprocessor_builder.py
  research/object_detection/builders/preprocessor_builder_test.py
  research/object_detection/core/keypoint_ops.py
  research/object_detection/core/keypoint_ops_test.py
  research/object_detection/core/preprocessor.py
  research/object_detection/core/preprocessor_test.py
  research/object_detection/dockerfiles/1.15/Dockerfile
  research/object_detection/dockerfiles/1.15/README.md
  research/object_detection/dockerfiles/2.2/Dockerfile
  research/object_detection/dockerfiles/2.2/README.md
  research/object_detection/model_lib_tf2_test.py
  research/object_detection/model_lib_v2.py
  research/object_detection/model_main_tf2.py
  research/object_detection/protos/hyperparams.proto
  research/object_detection/protos/preprocessor.proto
  research/object_detection/utils/config_util.py
Labels: cla: yes

#8717 Update maskrcnn_parser.py
  official/vision/detection/dataloader/maskrcnn_parser.py
Labels: cla: yes, ready to pull

#8739 Merged commit includes the following changes:
  research/object_detection/core/model.py
  research/object_detection/core/model_test.py
  research/object_detection/core/standard_fields.py
  research/object_detection/data_decoders/tf_example_decoder.py
  research/object_detection/data_decoders/tf_example_decoder_test.py
  research/object_detection/dataset_tools/context_rcnn/generate_detection_data_tf1_test.py
  research/object_detection/dataset_tools/context_rcnn/generate_embedding_data_tf1_test.py
  research/object_detection/dataset_tools/create_coco_tf_record.py
  research/object_detection/dataset_tools/create_coco_tf_record_test.py
  research/object_detection/export_tflite_ssd_graph_lib_tf1_test.py
  research/object_detection/exporter_lib_tf2_test.py
  research/object_detection/exporter_tf1_test.py
  research/object_detection/g3doc/context_rcnn.md
  research/object_detection/legacy/trainer_tf1_test.py
  research/object_detection/meta_architectures/center_net_meta_arch.py
  research/object_detection/meta_architectures/center_net_meta_arch_tf2_test.py
  research/object_detection/meta_architectures/faster_rcnn_meta_arch.py
  research/object_detection/meta_architectures/ssd_meta_arch.py
  research/object_detection/model_lib_tf2_test.py
  research/object_detection/model_lib_v2.py
  research/object_detection/model_main_tf2.py
  research/object_detection/models/faster_rcnn_inception_resnet_v2_keras_feature_extractor.py
  research/object_detection/models/faster_rcnn_inception_resnet_v2_keras_feature_extractor_tf2_test.py
  research/object_detection/models/faster_rcnn_resnet_keras_feature_extractor.py
  research/object_detection/models/ssd_mobilenet_v1_keras_feature_extractor.py
  research/object_detection/models/ssd_mobilenet_v2_fpn_keras_feature_extractor.py
  research/object_detection/models/ssd_mobilenet_v2_keras_feature_extractor.py
  research/object_detection/models/ssd_resnet_v1_fpn_keras_feature_extractor.py
  research/object_detection/predictors/convolutional_keras_box_predictor.py
  research/object_detection/protos/input_reader.proto
  research/object_detection/protos/train.proto
  research/object_detection/samples/configs/context_rcnn_resnet101_snapshot_serengeti.config
  research/object_detection/utils/bifpn_utils.py
  research/object_detection/utils/config_util.py
Labels: cla: yes

#8740 Merged commit includes the following changes:
  research/object_detection/builders/dataset_builder_test.py
  research/object_detection/dataset_tools/context_rcnn/add_context_to_examples_tf1_test.py
  research/object_detection/dataset_tools/context_rcnn/create_cococameratraps_tfexample_tf1_test.py
  research/object_detection/dataset_tools/context_rcnn/generate_embedding_data_tf1_test.py
  research/object_detection/dataset_tools/seq_example_util_test.py
  research/object_detection/dataset_tools/tf_record_creation_util_test.py
  research/object_detection/dockerfiles/tf1/Dockerfile
  research/object_detection/dockerfiles/tf1/README.md
  research/object_detection/dockerfiles/tf2/Dockerfile
  research/object_detection/dockerfiles/tf2/README.md
  research/object_detection/export_tflite_ssd_graph_lib_tf1_test.py
  research/object_detection/model_lib_v2.py
  research/object_detection/models/bidirectional_feature_pyramid_generators.py
  research/object_detection/models/bidirectional_feature_pyramid_generators_tf2_test.py
  research/object_detection/models/keras_models/hourglass_network.py
  research/object_detection/utils/model_util.py
Labels: cla: yes

#8741 Merged commit includes the following changes:
  research/object_detection/README.md
  research/object_detection/model_lib_v2.py
Labels: cla: yes

#8742 Merged commit includes the following changes:
  research/object_detection/meta_architectures/faster_rcnn_meta_arch.py
  research/object_detection/meta_architectures/ssd_meta_arch.py
Labels: cla: yes

#8751 Proper os path join for eval
  research/object_detection/model_lib_v2.py
Labels: cla: yes

#8753 Model export migration to TF2 and Additional shuffling when generating the TRAIN and VALIDATION datasets
  research/delf/delf/protos/delf_config.proto
  research/delf/delf/python/detect_to_retrieve/cluster_delf_features.py
  research/delf/delf/python/examples/extractor.py
  research/delf/delf/python/feature_aggregation_extractor.py
  research/delf/delf/python/training/build_image_dataset.py
  research/delf/delf/python/training/datasets/googlelandmarks.py
  research/delf/delf/python/training/model/delf_model.py
  research/delf/delf/python/training/model/export_global_model.py
  research/delf/delf/python/training/model/export_model.py
  research/delf/delf/python/training/model/export_model_utils.py
  research/delf/delf/python/training/model/resnet50.py
  research/delf/delf/python/training/train.py
Labels: cla: yes

#8716 Add Faster RCNN Resnet V1 FPN Keras feature extractor
  research/object_detection/builders/model_builder.py
  research/object_detection/models/faster_rcnn_resnet_v1_fpn_keras_feature_extractor.py
  research/object_detection/models/faster_rcnn_resnet_v1_fpn_keras_feature_extractor_tf2_test.py
Labels: cla: yes, stat:awaiting review

#8759 Update to the DELF training README
  research/delf/delf/python/training/README.md
  research/delf/delf/python/training/matched_images_demo.png
Labels: cla: yes
