Repository tensorflow/models, pull requests merged in 2021-11, with the labels that each got.

#10288 Assemblenet++ Migration with TF2
  official/vision/beta/projects/assemblenet/README.md
  official/vision/beta/projects/assemblenet/configs/assemblenet.py
  official/vision/beta/projects/assemblenet/experiment/ucf101_assemblenet_plus_tpu.yaml
  official/vision/beta/projects/assemblenet/experiment/ucf101_assemblenet_tpu.yaml
  official/vision/beta/projects/assemblenet/modeling/assemblenet.py
  official/vision/beta/projects/assemblenet/modeling/assemblenet_plus.py
  official/vision/beta/projects/assemblenet/modeling/assemblenet_plus_test.py
  official/vision/beta/projects/assemblenet/train.py
Labels: cla: yes, ready to pull

#10259 Added README.md
  research/delf/delf/python/training/global_features/README.md
  research/delf/delf/python/training/model/export_CNN_global.py
  research/delf/delf/python/training/model/export_model_utils.py
Labels: cla: yes, models:research

#10336 Roformer
  official/nlp/configs/encoders.py
  official/projects/roformer/README.md
  official/projects/roformer/__init__.py
  official/projects/roformer/experiments/roformer_base.yaml
  official/projects/roformer/roformer_attention.py
  official/projects/roformer/roformer_attention_test.py
  official/projects/roformer/roformer_encoder.py
  official/projects/roformer/roformer_encoder_block.py
  official/projects/roformer/roformer_encoder_block_test.py
  official/projects/roformer/roformer_encoder_test.py
  official/projects/roformer/roformer_experiments.py
  official/projects/roformer/train.py
Labels: cla: yes
