Repository tensorflow/models, pull requests merged in 2021-03, with the labels that each got.

#9763 "dataclasses;python_version<'3.7'" for https://github.com/tensorflow/…
  official/requirements.txt
Labels: cla: yes

#9764 "dataclasses;python_version<'3.7'" for https://github.com/tensorflow/…
  official/requirements.txt
Labels: cla: yes

#9765 "dataclasses;python_version<'3.7'" for https://github.com/tensorflow/…
  official/requirements.txt
Labels: cla: yes

#9768 Fix typo
  research/deeplab/README.md
Labels: cla: yes

#9769 Create __init__.py for `official/nlp/tools`
  official/nlp/tools/__init__.py
Labels: cla: yes, ready to pull

#9793 Add pylint wrapper extracted from TensorFlow CI.
  pylint.sh
Labels: cla: yes

#9803 Update tflite support version in workspace
  research/seq_flow_lite/WORKSPACE
Labels: cla: yes

#9796 Dataset utilities added.
  research/delf/delf/python/datasets/utils.py
  research/delf/delf/python/datasets/utils_test.py
Labels: cla: yes, stat:awaiting review

#9780 Add Wide & Deep by NVIDIA to community projects
  community/README.md
Labels: cla: yes, stat:awaiting review

#9817 moved to tensorflow/examples
  research/a3c_blogpost/README.md
  research/a3c_blogpost/a3c_cartpole.py
Labels: cla: yes

#9670 Moved check out of the loop to avoid quadratic runtime.
  official/nlp/data/tagging_data_lib.py
Labels: cla: yes, ready to pull

#9818 Create GitHub Action for pylint script.
  .github/scripts/pylint.sh
  .github/workflows/ci.yml
Labels: cla: yes

#9836 YT8M project: tested with pylint.sh
  official/vision/beta/projects/yt8m/README.md
  official/vision/beta/projects/yt8m/__init__.py
  official/vision/beta/projects/yt8m/configs/__init__.py
  official/vision/beta/projects/yt8m/configs/yt8m.py
  official/vision/beta/projects/yt8m/dataloaders/utils.py
  official/vision/beta/projects/yt8m/dataloaders/yt8m_input.py
  official/vision/beta/projects/yt8m/eval_utils/average_precision_calculator.py
  official/vision/beta/projects/yt8m/eval_utils/eval_util.py
  official/vision/beta/projects/yt8m/eval_utils/mean_average_precision_calculator.py
  official/vision/beta/projects/yt8m/experiments/yt8m.yaml
  official/vision/beta/projects/yt8m/experiments/yt8m_test.yaml
  official/vision/beta/projects/yt8m/modeling/__init__.py
  official/vision/beta/projects/yt8m/modeling/yt8m_agg_models.py
  official/vision/beta/projects/yt8m/modeling/yt8m_model.py
  official/vision/beta/projects/yt8m/modeling/yt8m_model_test.py
  official/vision/beta/projects/yt8m/modeling/yt8m_model_utils.py
  official/vision/beta/projects/yt8m/tasks/__init__.py
  official/vision/beta/projects/yt8m/tasks/yt8m_task.py
  official/vision/beta/projects/yt8m/yt8m_train.py
Labels: cla: yes, ready to pull
