Repository tensorflow/models, pull requests merged in 2021-05, with the labels that each got.

#9971 DeepMAC export script added (issue: 9966)
  official/vision/beta/projects/deepmac_maskrcnn/serving/detection.py
  official/vision/beta/projects/deepmac_maskrcnn/serving/detection_test.py
  official/vision/beta/projects/deepmac_maskrcnn/serving/export_saved_model.py
Labels: cla: yes, ready to pull

#9929 Update bot_config.yml
  .github/bot_config.yml
Labels: cla: yes

#10009 Added run superglue script
  official/nlp/finetuning/binary_helper.py
  official/nlp/finetuning/superglue/flags.py
  official/nlp/finetuning/superglue/run_superglue.py
Labels: cla: yes, ready to pull, stat:awaiting review

#9995 (doc) Add training log note to README.md
  README.md
Labels: cla: yes

#9923 YOLO Family: Updated model
  official/vision/beta/projects/yolo/configs/backbones.py
  official/vision/beta/projects/yolo/configs/darknet_classification.py
  official/vision/beta/projects/yolo/modeling/backbones/darknet.py
  official/vision/beta/projects/yolo/modeling/backbones/darknet_test.py
  official/vision/beta/projects/yolo/modeling/decoders/__init__.py
  official/vision/beta/projects/yolo/modeling/decoders/yolo_decoder.py
  official/vision/beta/projects/yolo/modeling/decoders/yolo_decoder_test.py
  official/vision/beta/projects/yolo/modeling/heads/__init__.py
  official/vision/beta/projects/yolo/modeling/heads/yolo_head.py
  official/vision/beta/projects/yolo/modeling/heads/yolo_head_test.py
  official/vision/beta/projects/yolo/modeling/layers/nn_blocks.py
  official/vision/beta/projects/yolo/modeling/layers/nn_blocks_test.py
Labels: cla: yes

#10027 YOLO Family: Linting
  official/vision/beta/projects/yolo/modeling/decoders/yolo_decoder.py
  official/vision/beta/projects/yolo/modeling/layers/nn_blocks.py
Labels: cla: yes
