Repository tensorflow/models, pull requests merged in 2021-06, with the labels that each got.

#10036 Merging DLRM model code into 2.5 branch.
  official/README-TPU.md
  official/README.md
  official/core/train_lib.py
  official/recommendation/ranking/README.md
  official/recommendation/ranking/__init__.py
  official/recommendation/ranking/common.py
  official/recommendation/ranking/configs/config.py
  official/recommendation/ranking/configs/config_test.py
  official/recommendation/ranking/configs/yaml/dcn_v2_criteo_tpu.yaml
  official/recommendation/ranking/configs/yaml/dlrm_criteo_tpu.yaml
  official/recommendation/ranking/data_pipeline.py
  official/recommendation/ranking/data_pipeline_test.py
  official/recommendation/ranking/task.py
  official/recommendation/ranking/task_test.py
  official/recommendation/ranking/train.py
  official/recommendation/ranking/train_test.py
  official/utils/testing/scripts/presubmit.sh
Labels: cla: yes

#10048 Update link to Embedding Colab
  research/audioset/vggish/README.md
Labels: cla: yes

#9906 Fix attention application in DELG
  research/delf/delf/python/training/model/delf_model.py
  research/delf/delf/python/training/model/delg_model_test.py
Labels: cla: yes

#10058 Merged commit includes the following changes:
  research/delf/delf/python/training/model/delg_model_test.py
Labels: cla: yes

#10022 Correct typo
  official/nlp/projects/mobilebert/README.md
Labels: cla: yes, ready to pull

#10076 Added factory method for Panoptic Mask R-CNN
  official/vision/beta/projects/panoptic_maskrcnn/configs/panoptic_maskrcnn.py
  official/vision/beta/projects/panoptic_maskrcnn/modeling/factory.py
  official/vision/beta/projects/panoptic_maskrcnn/modeling/factory_test.py
Labels: cla: yes

#10085 Fixed file link in README
  official/nlp/transformer/README.md
Labels: cla: yes

#10094 fixed typo for designed
  research/object_detection/README.md
Labels: cla: yes, models:research:odapi, ready to pull
