Repository tensorflow/models, pull requests merged in 2021-04, with the labels that each got.

#9861 Add NVIDIA DLRM to the community section
  community/README.md
Labels: cla: yes, stat:awaiting testing

#9871 Updated Intel-optimized community models
  community/README.md
Labels: cla: yes, stat:awaiting review

#9912 Fixed deprecated tf.flags
  research/attention_ocr/python/common_flags.py
  research/attention_ocr/python/datasets/fsns_test.py
  research/attention_ocr/python/demo_inference.py
  research/attention_ocr/python/demo_inference_test.py
  research/attention_ocr/python/eval.py
  research/attention_ocr/python/model_export.py
  research/attention_ocr/python/model_export_test.py
  research/attention_ocr/python/train.py
Labels: cla: yes

#9901 Global model supporting functions
  research/delf/delf/python/pooling_layers/pooling.py
  research/delf/delf/python/training/global_features_utils.py
  research/delf/delf/python/whiten.py
  research/delf/delf/python/whiten_test.py
Labels: cla: yes

#9894 Add NVIDIA EfficientNet to community models
  community/README.md
Labels: cla: yes, stat:awaiting review, stat:awaiting testing

#9725 [object detection] Bug fixes in colab tutorial
  research/object_detection/.gitignore
  research/object_detection/colab_tutorials/object_detection_tutorial.ipynb
  research/object_detection/utils/ops.py
Labels: cla: yes

#9210 Correct 404 link for object detection tutorial
  research/object_detection/g3doc/running_notebook.md
Labels: cla: yes

#9930 DELF codebase general cleanup
  research/delf/delf/__init__.py
  research/delf/delf/python/datasets/google_landmarks_dataset/compute_recognition_metrics.py
  research/delf/delf/python/datasets/google_landmarks_dataset/compute_retrieval_metrics.py
  research/delf/delf/python/datasets/google_landmarks_dataset/dataset_file_io_test.py
  research/delf/delf/python/datasets/revisited_op/dataset.py
  research/delf/delf/python/datasets/revisited_op/dataset_test.py
  research/delf/delf/python/datasets/utils.py
  research/delf/delf/python/datasets/utils_test.py
  research/delf/delf/python/delg/extract_features.py
  research/delf/delf/python/delg/perform_retrieval.py
  research/delf/delf/python/detect_to_retrieve/cluster_delf_features.py
  research/delf/delf/python/detect_to_retrieve/extract_aggregation.py
  research/delf/delf/python/detect_to_retrieve/extract_index_boxes_and_features.py
  research/delf/delf/python/detect_to_retrieve/extract_query_features.py
  research/delf/delf/python/detect_to_retrieve/perform_retrieval.py
  research/delf/delf/python/examples/extract_boxes.py
  research/delf/delf/python/examples/extract_features.py
  research/delf/delf/python/examples/match_images.py
  research/delf/delf/python/pooling_layers/pooling.py
  research/delf/delf/python/training/global_features_utils.py
  research/delf/delf/python/training/train.py
  research/delf/delf/python/whiten.py
  research/delf/delf/python/whiten_test.py
Labels: cla: yes

#9959 Disabling Tensorboard profiling for NCF.
  official/recommendation/ncf_keras_main.py
  official/recommendation/ncf_test.py
Labels: cla: yes

#9962 Catch tf.text NotFoundError:
  official/nlp/modeling/layers/text_layers.py
Labels: cla: yes

#9949 Add NVIDIA BERT
  community/README.md
Labels: cla: yes, stat:awaiting review
