Repository tensorflow/models, pull requests merged in 2021-01, with the labels that each got.

#9608 Fixed type in retinanet config
  official/vision/beta/configs/retinanet.py
Labels: cla: yes, ready to pull

#9536 YOLO Family: Darknet backbones
  official/vision/beta/projects/yolo/README.md
  official/vision/beta/projects/yolo/common/__init__.py
  official/vision/beta/projects/yolo/common/registry_imports.py
  official/vision/beta/projects/yolo/configs/backbones.py
  official/vision/beta/projects/yolo/configs/darknet_classification.py
  official/vision/beta/projects/yolo/configs/experiments/csp_darknet53.yaml
  official/vision/beta/projects/yolo/configs/experiments/csp_darknet53_tfds.yaml
  official/vision/beta/projects/yolo/configs/experiments/darknet53.yaml
  official/vision/beta/projects/yolo/configs/experiments/darknet53_tfds.yaml
  official/vision/beta/projects/yolo/dataloaders/classification_tfds_decoder.py
  official/vision/beta/projects/yolo/modeling/__init__.py
  official/vision/beta/projects/yolo/modeling/backbones/__init__.py
  official/vision/beta/projects/yolo/modeling/backbones/darknet.py
  official/vision/beta/projects/yolo/modeling/backbones/darknet_test.py
  official/vision/beta/projects/yolo/modeling/layers/__init__.py
  official/vision/beta/projects/yolo/modeling/layers/nn_blocks.py
  official/vision/beta/projects/yolo/modeling/layers/nn_blocks_test.py
  official/vision/beta/projects/yolo/tasks/image_classification.py
  official/vision/beta/projects/yolo/train.py
Labels: cla: yes, ready to pull

#9623 Update requirements.txt
  official/requirements.txt
Labels: cla: yes

#9607 README update for DELF training with autoencoder
  research/delf/delf/python/training/README.md
Labels: cla: yes

#9640 Update official/nlp/nhnet README.md
  official/nlp/nhnet/README.md
Labels: cla: yes, ready to pull

#9646 Update anchor.py
  official/vision/beta/ops/anchor.py
Labels: cla: yes

#9649 Revert "Update anchor.py"
  official/vision/beta/ops/anchor.py
Labels: cla: yes

#9644 Delete setup.py
  research/setup.py
Labels: cla: yes

#9648 Add NVIDIA implementation of ELECTRA to the community models
  community/README.md
Labels: cla: yes

#9637 Update vid2depth README.md
  research/vid2depth/README.md
Labels: cla: yes, models:research

#9669 Security Fix for Arbitrary Code Execution - huntr.dev
  official/modeling/hyperparams/params_dict.py
Labels: cla: yes, ready to pull

#9493 YOLO Family: Data Loaders
  official/vision/beta/projects/yolo/dataloaders/__init__.py
  official/vision/beta/projects/yolo/dataloaders/classification_tfds_decoder.py
  official/vision/beta/projects/yolo/dataloaders/decoders/__init__.py
  official/vision/beta/projects/yolo/dataloaders/decoders/tfds_coco_decoder.py
  official/vision/beta/projects/yolo/dataloaders/yolo_detection_input.py
  official/vision/beta/projects/yolo/dataloaders/yolo_detection_input_test.py
  official/vision/beta/projects/yolo/ops/__init__.py
  official/vision/beta/projects/yolo/ops/box_ops.py
  official/vision/beta/projects/yolo/ops/box_ops_test.py
  official/vision/beta/projects/yolo/ops/preprocessing_ops.py
  official/vision/beta/projects/yolo/ops/preprocessing_ops_test.py
Labels: cla: yes

#9686 Remove support for TRT in NVIDIA Electra description
  community/README.md
Labels: cla: yes
